### ISSUE TITLE
Mixer Tansition 2D - custom labels for X and Y

### ISSUE THREAD

**Issue by nehvaleem** [KybernetikGames/animancer#104]
Hi, 
I am new to the animancer and loving it so far. I've got one question regarding mixer transitions, sorry if it's the wrong place to ask such, but I couldn't find any better. 

My question is: is it possible to set custom labels for the 2D Mixer Transition? X and Y are quite fine, but I would create a mixer transition for idle with two parameters: Injury and Anger, for example. It would be much easier to work with if someone could change the labels to be more appropriate.

**Comment by KybernetikGames** [comment]
Changing the labels in the Inspector should be easy enough to implement with something along the lines of the [Event Names Attribute](https://kybernetik.com.au/animancer/docs/manual/events/animancer/#event-names).

The main reason I haven't done it already is that in code you would still need to access them using the `X` and `Y` properties.

**Comment by KybernetikGames** [comment]
I'm considering implementing this feature soon, but when I look at the Inspector there's already very little room to work with so allowing the labels to take up more room seems like it wouldn't be very helpful.
![image](https://user-images.githubusercontent.com/43698611/128114926-937dbd88-b2ee-475a-9198-27e4e6bc1e9e.png)
What if instead of replacing the `X` and `Y` in all rows, it lets you replace the `Threshold` header with something like `Injury / Anger` or `X: Injury, Y: Anger`?

**Comment by KybernetikGames** [comment]
[Animancer v7.1](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-1) is now available with a new `[ThresholdLabel]` attribute to change the header.
