### ISSUE TITLE
in edit mode, root motion is not working  

### ISSUE THREAD

**Issue by fofewyoung** [KybernetikGames/animancer#107]
i just play a simple animation clip,  use below code:

```
            var state = animancerComp.Play(inputClip);
            state.NormalizedTime = normalisedTime;
            state.Weight = 1.0f;

            animancerComp.Evaluate();
            animancerComp.Playable.PauseGraph();
```

i found root motion is not working too in TransitionPreviewWindow's inspector
how to apply rootmotion in editmode?

**Comment by KybernetikGames** [comment]
You'll need to use `((IPlayableWrapper)state).Playable.SetTime(time);` (or `time * clip.length` for the normalized time).

The reason Animancer's `Time` and `NormalizedTime` properties don't do that is because of the way Animation Events work. Calling `SetTime` once will trigger all events between the old time and the new time which is usually not what you want so Animancer calls `SetTime` twice to avoid that. Apparently that causes different behaviour for Root Motion as well.

**Comment by fofewyoung** [comment]
that's great,  it works!
thanks very much
