### ISSUE TITLE
Parent animation states / animation "container" 

### ISSUE THREAD

**Issue by joshcamas** [KybernetikGames/animancer#110]
# Use Case
One gain of using animancer + animation controllers is the "modularity" of being able to crossfade between animation controllers. The controllers themselves contains layers, state machines and more, and you merely need to fade the controller in and out. Awesome! But what if you want to replace the animator controllers with animancer logic (such as a state machine)? Now you can no longer easily fade in and out a single object containing whatever cool animation logic inside of it, and instead now need to somehow keep track of layers and all sorts of whacky stuff. 

# Solution

One very powerful solution would be to allow the creation of package "containers". This would be similar to a animator controller, but of course allowing the use of animancer functions. Then these containers themselves could have transitions themselves! Here's an example:

var container = new Container()
container.Play(myClip,0) 
container.FadeIn(myMixer,2) 
animancer.FadeIn(container) 

Later... 

animancer.FadeOut(container) //doesn't matter what's going on inside of container, it'll fade similarly to a controller

This essentially allows for layers specifically to be "packed away" into their corresponding containers (which is really just an animation state, as you can see). 

This is very similar to how unreal works (in the sense that layer blending can be done inside of a individual animation state, instead of at the highest level), and could absolutely unlock SO much potential.

**Comment by joshcamas** [comment]
The reason why having at least one level of nesting is so powerful is the same reason why blending between controllers is so awesome. You get a modularized level of layers. In my case, I have a bunch of controllers that act as "weapon controllers", and when the player switches weapons, the main controller fades in. Each controller is able to have its own layer logic, such as where the mask is, or even the number of layers.

The most powerful implementation would allow layers to be manipulated at a lower level. This could mean you could blend between (layer1: clip, layer2: clip) and (clip), which could be pretty amazing, instead of having the layers be managed at the highest level. This can allow systems such as a weapon controller to do its own thing, while other systems can do their own thing as well (and have some sort of blending / masking / whatever needs to be done) without having the two systems need to worry about wonky layer collision or something.

![Screenshot_48](https://user-images.githubusercontent.com/26180637/114316828-24fbac00-9aba-11eb-8455-d5b38f3e55e8.png)

However, this is obviously adding a LOT of complexity. One possible way to simplify this heavily is to essentially allow containers to act as powerful as controllers and no more. Aka a "coded" controller. This type of container would have its own layer management, and... that's it. Nothing else. HOWEVER, no matter how many layers the container, you can easily blend between containers via (container.FadeIn()). This modularizes things, just like how using controllers modularizes things.

![Screenshot_49](https://user-images.githubusercontent.com/26180637/114316830-27f69c80-9aba-11eb-8137-4ddfd345ec04.png)

**Comment by KybernetikGames** [comment]
I'm having a hard time visualising what the practical implementation would really look like. For example: what are all of those states in your diagrams? References to Animation Clips? `ClipState.Transition`s? Any kind of transitions? How are they referenced in code? Perhaps you could try comparing your idea to the [Weapons](https://kybernetik.com.au/animancer/docs/examples/fsm/weapons/) example to explain how you would improve the workflow and/or simplify the user code?

It would be quite easy to make a `LayerDefinition` class to let you set up layer details (mask, additive, editor name) in the Inspector and apply them with a single method call, but that doesn't seem like it would actually be too useful since layer operations kind of need to be hard coded anyway. Like in the [Layers](https://kybernetik.com.au/animancer/docs/examples/layers/) example when the animation ends on the Upper Body layer and it fades that layer out, it needs to explicitly know that the animation was played on an extra layer so that fading it out will let the base layer take over on its own, otherwise it would need to actually tell it to play the Idle animation rather than fading the layer out.

`AnimancerPlayable`s can't be faded. It would be possible to implement, but would take a bunch of work and add some runtime overhead and I don't think you would really achieve anything by doubling up on the things it's responsible for. The result would probably be pretty similar if you just fade out all layers except the base and play whatever new transitions you want.

**Comment by joshcamas** [comment]
In my case, I do not attach my code logic of individual weapons to a single class. This allows different weapons to have their own modularized input logic. I currently have the same thing for animations, using animation controllers - each weapon has its own animation controller, and thus the animation logic between weapons is disconnected. The idea of this system is that it really doesn't matter what is inside of a container, just like how it doesn't really matter what is inside of a animation controller.

I guess what I can try to do is build an automatic layer manager, that keeps track of layers playing, and when you transition to a animation that isn't meant to be "layered", it will fade in it on a "top" layer that overrides everything, and fades out the lower layers. Messy, but it could work.

**Comment by KybernetikGames** [comment]
I think a layer manager that understands whatever different types of layers you have and can use them intelligently would be much better than a dumb system that would basically need to create separate layers for each container to ensure that they don't interfere with each other.
