### ISSUE TITLE
StateMachine is nullified on script reloads, is there any way to avoid this?

### ISSUE THREAD

**Issue by Bonfyre90** [KybernetikGames/animancer#113]
As the title suggests do I just need to restart my game every time I reload scripts? Or am I missing something obvious here.

I have States that I am serializing so they retain data specific to the StateMachine, but this data is lost and it causes all kinds of errors, even if I recreate the StateMachine in the OnEnabled rather than OnAwake.

Any help on this matter is greatly appreciated.

**Comment by KybernetikGames** [comment]
I just set Unity to not recompile until after leaving Play Mode because I do way too much stuff that can't survive script reloads so I'm not too familiar with what needs to be done, but in this case I think it might be possible.

1. Open StateMachine1.cs and change the `CurrentState` property to use a serialized field:
```
[SerializeField]
private TState _CurrentState;

/// <summary>The currently active state.</summary>
public TState CurrentState { get => _CurrentState; set => _CurrentState = value; }
```
2. Make a serializable sub-class:
```
[System.Serializable] public class YourStateMachine : StateMachine<YourStateType> { }
```
3. Use that sub-class as your field type and make it serialized:
```
[SerializeField] YourStateMachine _StateMachine;
```
That should allow it to survive script reloads so I think you just need to initialise it in `Awake` like normal.

**Comment by Bonfyre90** [comment]
Seems like there's a lot of data that doesn't survive a reload, would take me too long to figure it all out. That worked until I tried to access a states State variable.

**Comment by KybernetikGames** [comment]
I've looked into the issue a bit more and found that trying to support hot reloads would require significant workarounds all over the system which wouldn't be worth the effort so I'm closing this issue for now (but I could revisit it later if more people want it).
