### ISSUE TITLE
Editor Gives me errors each time I exit playmode

### ISSUE THREAD

**Issue by robert-irribarren** [KybernetikGames/animancer#119]
# Environment

- Animancer Version Number:  Animancer pro v6.1 
- Animancer Pro or Lite:  pro
- Unity Version: 2019.4.15f1
- Platform:  Windows

# Description
NullReferenceException: Object reference not set to an instance of an object
Animancer.AnimancerPlayable.GetKey (UnityEngine.AnimationClip clip) (at Assets/Plugins/Animancer/Internal/Core/AnimancerPlayable.cs:523)
Animancer.AnimancerPlayable+StateDictionary.GetOrCreate (UnityEngine.AnimationClip clip, System.Boolean allowSetClip) (at Assets/Plugins/Animancer/Internal/Core/AnimancerPlayable.StateDictionary.cs:232)
Animancer.AnimancerPlayable.Play (UnityEngine.AnimationClip clip) (at Assets/Plugins/Animancer/Internal/Core/AnimancerPlayable.cs:535)
Animancer.AnimancerUtilities+<>c__DisplayClass21_0.<EditModePlay>b__0 () (at Assets/Plugins/Animancer/Internal/Core/AnimancerUtilities.cs:397)
UnityEditor.EditorApplication.Internal_CallDelayFunctions () (at <a8e33794c0064f2aa201ade069162226>:0)

# Reproduction

Steps to reproduce the bug:

1. Create an animator and animation for a spriterenderer
2. add an animancer component
3. Idk what I did but something
4. ???
5. See the error in the Console.

http://prntscr.com/138bsuj
![image](https://user-images.githubusercontent.com/4400640/119179274-961c7080-ba23-11eb-8532-276722e8f9cd.png)

![image](https://user-images.githubusercontent.com/4400640/119179352-a896aa00-ba23-11eb-90ef-5fbef207296e.png)

![image](https://user-images.githubusercontent.com/4400640/119179369-ae8c8b00-ba23-11eb-8f9e-f2ad790960fe.png)

![image](https://user-images.githubusercontent.com/4400640/119179397-b64c2f80-ba23-11eb-9a0b-44f4ac5b05d2.png)

```
using Animancer;
using UnityEngine;

public class SelectionArrow : MonoBehaviour
{
    public HybridAnimancerComponent animancer;
    public SpriteRenderer spriteRenderer;

    public void OnSelected()
    {
        spriteRenderer.enabled = true;
        AnimancerState state = animancer.Play("SelectionActive", -1, 0f);
    }

    public void AnimationEventHideArrow()
    {
        spriteRenderer.enabled = false;
    }
}
```

**Comment by KybernetikGames** [comment]
That's very strange. For `AnimancerPlayable.GetKey` to throw a `NullReferenceException`, its `Component` must be null. But the only place the `Component` is set is the `SetOutput` method which the `AnimancerComponent` passes `this` into so it should never be null (and it has to actually be null, not just destroyed because it would actually still work if it was only destroyed).

See if you can figure out how to reliably replicate the issue, because I don't think I'll be able to fix it properly unless I can replicate it.

**Comment by robert-irribarren** [comment]
![image](https://user-images.githubusercontent.com/4400640/119215060-1ec8fa00-ba80-11eb-971a-a5ddd497301a.png)
Component is null!

I am able to reproduce it by changing any .cs file and when the code recompiles it hits the breakpoint

**Comment by KybernetikGames** [comment]
`return clip` would be better since that's what the base `AnimancerComponent` does, but the `Component` is still null meaning there must be a bug somewhere else that's not initialising the system properly.

To debug it we'd need a `Debug.Log` in `SetOutput` to log its parameters, which would be pretty annoying if you have to leave it there indefinitely since we don't know how to actually replicate the issue.

**Comment by robert-irribarren** [comment]
I updated my post to use the return clip.

**Comment by KybernetikGames** [comment]
You can't play animations on a prefab since it's not in the scene. That should actually throw an exception instead of returning.

**Comment by KybernetikGames** [comment]
In `AnimancerPlayable.SetOutput` I've changed it to:

```
if (UnityEditor.EditorUtility.IsPersistent(animator))
    throw new ArgumentException(
        $"The specified {nameof(Animator)} component is a prefab which means it cannot play animations.",
        nameof(animator));
```

And in `AnimancerUtilities.EditModePlay` I've changed the nested `ShouldPlay` method to:

```
if (UnityEditor.EditorApplication.isPlayingOrWillChangePlaymode ||
    animancer == null ||
    animancer.Animator == null ||
    clip == null ||
    UnityEditor.EditorUtility.IsPersistent(animancer.Animator))
    return false;
```

**Comment by KybernetikGames** [comment]
[Animancer v7.0](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-0/) is now available with this fix in it.
