### ISSUE TITLE
Some notes while reading the User Manual

### ISSUE THREAD

**Issue by LarsJandel** [KybernetikGames/animancer#12]
- Edit Mode - `AnimancerUtilities.EditModePlay`: interesting details in the script explanation
- `CalculateThresholdsFromAverageVelocityXZ` sounds nice to get a proper threshold - could be showcased maybe? e.g comparing the different possible threshold algorithms to achieve a clean transition between idle, walking slow to an exaggerated run, while just using the idle, walk and run animations
- missing/broken screenshot link at Blending/Mixers/example expand "⯈ The following example script uses a LinearMixerState to blend between Idle and Run animations based on a Movement Speed slider in the Inspector:" (I think, another picture was missing somewhere else before...)
- "Foot Phase Synchronisation": yep, sounds interesting indeed 😉
    -> reminds me a bit of - looking at composing music - Ableton Live's Warp Markers to correctly pin samples to a rhythm. These get created automatically via analysis first but can be modified/optimized by the user https://www.ableton.com/en/manual/audio-clips-tempo-and-warping/#9-2-2-warp-markers
- Events:
    - Overview:
        - same info at top and bottom
        - hm, when reading the table left to right, comparing the two systems, it can be bit confusing as on both sides the general term "events" is used. Even if it might be repetitive, always using the full definition "Animation Events" and "Animancer Events" could help. Also, could be helpful to mention the two options - UnityEvents and UltEvents - at the top, as they are just used in the table before explaining them briefly
    - Animation Events:
        - Crossfade: v3 leftover?
    - Animancer Events:
        - so cool to set clip independent events in the inspector (or code) - no need to duplicate read-only animation clips 🤘
        - even better to preview the set time in the Transition Preview Window! 
- Finite State Machines:
    - hyperlinks do not lead to the desired destination anymore or have expired: "There are plenty of other FSM systems available online (including on the Unity Asset Store), or if you’re interested in implementing your own system Unity has a tutorial series about building a Finite State AI which could easily be adapted for other purposes."
    - will have to read this chapter again as it is a bit difficult for me to wrap my head around regarding TKey, TState, IState, IOwnedState, DelegateState
- Animator Controllers:
    - v3 leftover I guess: CrossFade
    - Hm, I don't see a dropdown in the screenshot on this page: "Using their Transitions gives you a helpful dropdown menu in the Inspector for selecting the parameter name(s) as shown in the image at the top of the page."

Thanks

**Comment by KybernetikGames** [comment]
`CalculateThresholdsFromAverageVelocityXZ` is tricky because I don't actually have any appropriate animations to demonstrate it with. It's only for the 2D Mixers, but the only example that uses one is the Spider Bot model which won't work because its animations don't use root motion.

But I've addressed the rest of those suggestions:

- I clarified the terminology in the Events table as you suggested.
- The `CrossFade` methods on the Events page aren't leftovers. They need different method names because Unity's Animation Events can't distinguish between method overloads like regular code.
- Same for `CrossFade` on the Animator Controllers page. It's a simple wrapper around the `CrossFade` method in Unity's `AnimationClipPlayable` so it has the same name.
- Fixed the FSM links. Seems like they changed their link structure and the tutorial I was linking to seems to be gone entirely or maybe renamed.
- Improved the FSM explanations, added an example for Owned States, and various links to the C# in Unity section including new explanations of Extension Methods and Generics.
- The Parameter Controllers section now links to the right area of the Transition Types page which does show the dropdown in a screenshot.
