### ISSUE TITLE
why animancer not have a method like Animator.CrossFadeInFixedTime

### ISSUE THREAD

**Issue by brucelits** [KybernetikGames/animancer#124]
In the last question I got a function
 
```
void _MoveNormalizedTime(AnimancerState state, float normalizedTime)
{
	((IPlayableWrapper)state).Playable.SetTime(normalizedTime * state.Length);
	var count = state.ChildCount;
	for (int i = 0; i < count; i++)
	    _MoveNormalizedTime(state.GetChild(i), normalizedTime);
}
```

it can work, but in the first frame of fade duration only the next animation can contribute rootMotion, it means in that frame rootMotion is less than expect.

**Comment by KybernetikGames** [comment]
Immediately after you call `Play(clip, fadeDuration)` the state will still be at 0 weight because the fade hasn't actually started yet, so that animation won't cause any root motion if you move its time in that frame.

You could try something like this:

```
var state = animancer.Play(clip);// No fade so Weight is now 1.
_MoveNormalizedTime(state, normalizedTime);// Now the root motion should apply fully.
animancer.Evaluate();// Apply the animation graph to the character.
state.Weight = 0;// Start back at 0 weight.
state.StartFade(1, fadeDuration);// Fade in.
```

That would give you more root motion than playing it naturally though, because the start of the animation will be applying its motion at 1 weight instead of only a portion of it as it fades in. To avoid that, you would need to incrementally adjust the weight and move the time to call `Evaluate` for each frame of the fade individually because the Playables API has no fade system, it's just weights which Animancer has to modify over time.

What are you actually trying to do? Maybe there's a different way to approach the problem.

**Comment by brucelits** [comment]
I want to play animancer like animator transition work. in animator,  if i make a transition form state A to state B, and set transition offset and fade duration. in the frame of A→B,  rootMotion = A * weightA + B * weightB, if transition trigger time is close beging of the frame, rootMotion is close to animation A`s rootMotion, if transition trigger time is close end of the frame, rootMotion is close to animation B`s rootMotion.in animancer how should i do that.

**Comment by KybernetikGames** [comment]
If you make a minimal reproduction project showing an Animator Controller giving you the root motion you want and email it to animancer@kybernetik.com.au, I'll see if I can figure out how to get the same result with Animancer. But it might not be possible at all because the Playables API doesn't give us access to everything that Animator Controllers can do.

**Comment by brucelits** [comment]
thank you, I send a email to you.

**Comment by KybernetikGames** [comment]
I've had a look at your project and unfortunately I don't think it's possible to get that level of sub-frame precision using the Playables API. The Animator Controller knows when an animation will end and also knows exactly what transition will occur beforehand so it's able to plan ahead, but Animancer only knows what the next transition looks like when you tell it to actually start that transition at which point it has already applied some of the motion you didn't want.

Your best option might be to [play an Animator Controller within Animancer](https://kybernetik.com.au/animancer/docs/manual/animator-controllers/) for the animations you need precise root motion on and use separate animations for other things so you can still make use of Animancer's advantages for the rest of your system.

**Comment by brucelits** [comment]
thank you, I will try some other method
