### ISSUE TITLE
Best way to read per-layer AnimationStream data before layer mixing

### ISSUE THREAD

**Issue by LudiKha** [KybernetikGames/animancer#125]
Hi,

I'm trying to blend an upperbody & lowerbody animation, by reading and comparing the hip & spine bone rotations of both clips before they will be masked and layer mixed.

Animancer currently supports inserting output jobs, that does allow me to read the final layermixed AnimationStream. However, I need to read the individual AnimationStreams for both layer 0 and 1.

In an output job immediately after the AnimancerPlayable, I'm able to get a single parent input stream, but the inputStreamCount is 0 for that one (so unable to traverse this to get to the layers).

Is there a way to access individual bone rotations (ideally in the AnimationStream) whilst layer mixing?

**Comment by KybernetikGames** [comment]
You probably shouldn't try to intercept both layers at once because they still need to be connected to their mixer, but you could make one job for each layer and insert it between the layer and the mixer like this:

```
var layerMixer = ((IPlayableWrapper)animancerComponent.Playable).Playable;
var graph = animancerComponent.Playable.Graph;
var yourPlayable = ...// Create your job playable.

var layer = layerMixer.GetInput(x);// Get the layer.
graph.Disconnect(layerMixer, x);// Disconnect the layer from the mixer.

graph.Connect(layerMixer, x, yourPlayable, 0);// Connect your playable to the mixer.
yourPlayable.SetInputWeight(0, 1);

graph.Connect(yourPlayable, 0, layer, 0);// Connect the layer to your playable.
yourPlayable.SetInputWeight(0, 1);
```

Then you just need to pass the data over from the first job to the second or maybe from both of them to an output job where you do the work. [The native array trick I described here is handy for passing data in and out of jobs](https://kybernetik.com.au/animancer/docs/examples/jobs/lean/#angle).

**Comment by LudiKha** [comment]
This totally worked, fantastic thank you! I've banged my head on this for the past few days and to have a solution that's so elegant is very satisfying.

One final thing - my layers are enabled/disabled at runtime so I need a way to insert the jobs whenever this happens. Could you recommend the preferred way to hook into the playable graph changes?

**Comment by KybernetikGames** [comment]
The simplest way would be to just set [AnimancerPlayable.KeepChildrenConnected](https://kybernetik.com.au/animancer/api/Animancer/AnimancerPlayable/FEFD6C35) to true so it never disconnects them.

Adding a second `Playable` to `AnimancerLayer` could have unforseen consequences because the system expects each `AnimancerNode` (layers and states) to have a single `Playable` which can be accessed by its parent and children so it would need some testing to figure out if layers are actually being accessed from both directions or not.

**Comment by LudiKha** [comment]
Thanks a bunch, this will certainly do the trick. 💯
