### ISSUE TITLE
The scale doubles when I moved a AnimancerState into another layer

### ISSUE THREAD

**Issue by muscly** [KybernetikGames/animancer#127]
# Scenario
1. Play clip A in layer 0
2. Play clip B in layer 1
3. Set B's layer to 0

# Result
* Both A & B states have weight 1.
* And the scale of some bone gets double.
** (The scaling curves for that bone in clips A & B have value 1).

![image](https://user-images.githubusercontent.com/1177389/122035240-3c824880-ce0d-11eb-96df-9fc7ea378b7c.png)
![image](https://user-images.githubusercontent.com/1177389/122035321-50c64580-ce0d-11eb-868e-7491e18b42e2.png)

# Additional Tests
* When I adjusted one of the weights manually in the inspector, they became 0.5 and 0.5 automatically. And the scaling problem was gone.

# Expected Result
## Prefered Result
* Clips A & B are blended in half and half with weight 1, just like legacy Animation.
## If it's not possible
* The weights of all states in the layer are adjusted properly when I moved the state into the layer.

# Comments
Hi. I'm happy to find this project Animancer and love it.
I wonder this problem is caused by Animancer or Playable.
Thank you for reading.
looking forward to your answer.

**Comment by KybernetikGames** [comment]
Auto Normalize Weights is one of the [Display Options](https://kybernetik.com.au/animancer/docs/manual/playing/inspector/#display-options) for the Inspector, which is why you're only seeing that behaviour there. It's there for convenience so you can just drag the weight of one state and the others will adjust accordingly, but it's optional and not applied in the actual runtime code because there are situations where you could make use of weights not adding up to 1 or you might actually want different behaviour such as to keep the state you moved at its current weight and reduce all others instead.

If you have Animancer Pro, open the *Assets/Plugins/Animancer/Internal/Interfaces/IPlayableWrapper.cs* script and add the following method to the `AnimancerEditorUtilities` class down the bottom:

```
/// <summary>Re-scales the <see cref="AnimancerNode.Weight"/> of all children to add up to 1.</summary>
public static void NormalizeChildWeights(this IPlayableWrapper parent)
{
    var totalWeight = 0f;
    var childCount = parent.ChildCount;
    for (int i = 0; i < childCount; i++)
    {
        var child = parent.GetChild(i);
        if (child.IsValid())
            totalWeight += child.Weight;
    }

    if (totalWeight == 0 ||// Can't normalize.
        Mathf.Approximately(totalWeight, 1))// Already normalized.
        return;

    totalWeight = 1f / totalWeight;
    for (int i = 0; i < childCount; i++)
    {
        var child = parent.GetChild(i);
        if (child.IsValid())
            child.Weight *= totalWeight;
    }
}
```

Or if you're using Animancer Lite, just put it in any `static` class and remove it next time you update Animancer since I'll include it in the next version.

Then you can just call `animancer.Layers[x].NormalizeChildWeights();` when you move the state.

**Comment by muscly** [comment]
Thank you for your quick response.
I was looking into the code to find that. :)
But, I think normalizing weights is the next best option.

I have one more question. 
**Is there no way to fix this problem without normalizing weights?**
I want to know if this problem is caused by my animation clips or other system parts.

**Comment by KybernetikGames** [comment]
There's nothing wrong with your animations. The "problem" is simply that having non-normalized weights is perfectly valid and is working as expected, it's just not commonly desirable and doesn't happen under normal circumstances.

If you want it to happen automatically, you could go to the `AnimancerState.SetParent` method and call it there.

**Comment by muscly** [comment]
Oh, I didn't expect you to reply immediately. 👍 
My explanation was insufficient.
My problem is not having non-normalized weights but having doubled scales in some bones when a layer has non-normalized weights.

The blue one is animated by Animancer (Pro) and the red one is animated by legacy Animation.
They are using the same animation clip. (Of course, a cloned one for using different animation types)
The L-thigh and R-thigh bones are scaled up to twice only in the blue one.

![image](https://user-images.githubusercontent.com/1177389/122141258-ebfc0100-ce87-11eb-94d5-b8a6c7287503.png)

**Comment by KybernetikGames** [comment]
They shouldn't affect the scale if none of your animations are actually animating the scale. Open the Animation window and check if your animations have properties for scale (and remove them if you don't need them because animating scale is actually very inefficient).

**Comment by muscly** [comment]
Yes, I'll check it again.
Thank you for your support. 😄

**Comment by muscly** [comment]
I'm afraid that I have one more question.
Just setting the weight of the state to 2 makes the scales of bones double. 
Is this normal in Animancer and Playable? Or is it caused by my clips?

**Comment by KybernetikGames** [comment]
I don't see it happen on any of the example animations (they obviously look wrong, but they don't scale unexpectedly).

If you want to just send me your animation I'd be happy to take a look at it.

**Comment by muscly** [comment]
I sent you the sample project via email under the title of 'A Sample Project for Issue #127 and #129'.

**Comment by KybernetikGames** [comment]
If you look at the animation in the Animation window you can see that it has Scale values on almost all of its bones (all of which are setting the scale to a constant value). Basically, Unity is just applying `AnimationValue * Weight` for all the animated values which you don't notice when they all add up to 1, but when they don't you see the scale change. Removing those properties from the animation fixes the issue:

- To do it in Unity, you need to duplicate the animation out of the FBX by selecting it and pressing CTRL + D because Unity can't directly edit FBX files. That means you'd need to do it all again if you modify and re-export your model.
- Most likely the actual cause is a setting in your modelling program's exporter which you should just disable and re-export the model. Possibly something in the animation data itself, I'm not very familiar with the modelling side of things.

![image](https://user-images.githubusercontent.com/43698611/122360098-7a13dc80-cf99-11eb-8ca2-80e39899c36a.png)

**Comment by muscly** [comment]
Thank you. I wanted to know if this phenomenon is intended by Unity.
Our clips have scale bones for some reason. And we used this way for several years with Legacy Animation.
Then, I think the only way is to normalize the weights. But It seems too difficult to normalize the weights while fading states and layers at the same time.
Anyway, I'm glad to get to know this is intended.
