### ISSUE TITLE
Blending between the states in different layers.

### ISSUE THREAD

**Issue by muscly** [KybernetikGames/animancer#130]
Hi! 
I have a question about best practices in using Animancer.

When there is only one state in a layer and the weight of the state is something inside 0 and 1, it seems that the state blends with the T-pose (or the default states of the game object).
What I want is to make a state in a higher layer blend with a state in a lower layer.
(This is the default behavior of Legacy Animation.)

The only way I know in Animancer is to fade the higher layer instead of the state in it.
If this is the only way, I have to make some system to adjust the weights of states and layers according to the circumstances.
Please let me know if there is a handy way to achieve this.

Thank you.

**Comment by KybernetikGames** [comment]
Layer mixing is different from the mixing of states within a layer. I don't know exactly what they do internally, just that one uses an `AnimationLayerMixerPlayable` while the other uses an `AnimationMixerPlayable` so any differences in the way they blend is likely by design and can't be modified by Animancer.

Someone else had a similar problem earlier today in the forum thread and I [came up with a potential explanation for what's happening internally](https://forum.unity.com/threads/animancer-less-animator-controller-more-animator-control.566452/page-21#post-7245536), but that's really just a guess.

So most likely you will need to adjust the layer weight instead of the state weight.

**Comment by muscly** [comment]
Thank you. I always appreciate your quick and helpful support.
