### ISSUE TITLE
How to rewind animations using Animancer?

### ISSUE THREAD

**Issue by nehvaleem** [KybernetikGames/animancer#137]
I am trying to wrap my head around reversing the time in my game. How should I approach reversing the animations that are being played with animancer?

**Comment by KybernetikGames** [comment]
You can just set the speed of the animation to `-1`. The [Spider Bot](https://kybernetik.com.au/animancer/docs/examples/fine-control/spider-bot/) and [Doors](https://kybernetik.com.au/animancer/docs/examples/fine-control/doors) examples demonstrate how to manipulate speed and time.

**Comment by nehvaleem** [comment]
Yeah, but then I will have to manage all the transitions by myself right? I was curious if there are methods like StartRecording(), StartPlayback() and others like they are in the Animator component.

**Comment by KybernetikGames** [comment]
It might be possible to implement, but there's nothing like that at the moment.

**Comment by nehvaleem** [comment]
That would be awesome, thanks!

**Comment by KybernetikGames** [comment]
I've thought about it a bit more and realised that implementing such a system within Animancer would require significantly more complexity than the Animator system likely has due to the flexibility Animancer exposes. For example, it would need to track the creation of states, moving states between layers, the parameters of any `MixerState`s and `ControllerState`s, enabling or disabling IK, or even changing the `AnimationClip` used by a `ClipState`. To do that, it would basically need to clone every active state every frame during the recording, which seems like it would be quite bad for performance.

Instead, it might be better to use an external solution which simply records the rotations of all bones every frame. That would mean you need to manually specify which bones and other properties you want it to track (since you can't get that info from an `AnimationClip` or `Animator` at runtime), but it would also allow the system to work on any objects independent of the animation system so it would work for anything (such as physics objects). You might even be able to find a system someone has already made. I know Unity has a Game Object Recorder system, but it's Editor-Only since it's designed to save actual `AnimationClip`s rather than simply replay what it recorded (though that package might be a good starting point for making a replayable system).

Either way, a large new feature like this won't make it into the upcoming [Animancer v7.0](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-0/) since it already has the longest Change Log of any version so far and I need to actually release it so I can work on other projects.
