### ISSUE TITLE
Mixer Transitions: Array commands duplicate and delete do not work properly

### ISSUE THREAD

**Issue by LarsJandel** [KybernetikGames/animancer#140]
# Environment

- Animancer Version Number: 7
- Animancer Pro or Lite: Pro
- Unity Version: 2021.1.15f1
- Platform: Windows 10

# Description

When using e.g. a `MixerTransition2D` and using the RMB context menu commands _Duplicate Array Element_ and _Delete Array Element_, the behaviour is not as expected:

Duplicate Array Element:
It does create a new array entry at the correct position and duplicates the _Animation_ , but won't duplicate the other column entries like _Threshold_ etc., the previous value entries will stay in place, no matter if array elements get duplicated in between, resulting in wrong value entries. Previous later array entries will be readded(?) to the extended array not with their previous values but with the same as the last one, similar to using the **+** button. 

Delete Array Element:
Well, it does delete some _Animation_, but doesn't delete the array item, the list doesn't get shorter, just mixing up everything.

# Reproduction

Steps to reproduce the bug:

You can try it e.g. without even openening a scene with the scriptable object within `03 Locomotion/02 Linear Blending/Linear Locomotion Mixer Transition` 

---

Here's a screen recording: I made the window wider as usual in order for you to see the entries to the right while trying the operations.

Thanks!

https://user-images.githubusercontent.com/32457827/127732550-f964ca6f-996a-4b5f-bdbd-120fa6d69a3f.mp4

**Comment by KybernetikGames** [comment]
The issue is that each of those columns is actually a separate array so you're duplicating the animation then it sees that the others are the wrong size and resizes them, but Unity doesn't give any way to know what you did to change the array size so my drawer has no way to decide what the new values in the other arrays should be or how they should be organized. The buttons at the bottom of the reorderable list only work because it has inbuilt callbacks for me to replace their default functionality.

There are two reasons why they're all separate arrays instead of a single array of structs/classes:

- The `Speed` and `Sync` values are often unused so their arrays can be smaller than the number of animations to reduce build size and improve serialization performance. In your video, the `Speed` array would actually be empty and the `Sync` array would only contain a single element to indicate that the first value is false. All the other values are just display dummies unless you put a different value there.
- The animations array is defined in the base `ManualMixerTransition<TMixer>` which is the parent of manual mixers (no thresholds), linear mixers (`float` thresholds), and 2D mixers (`Vector2` thresholds). Having the animation and threshold in the same array would mean they'd need to be defined in the same class, so that base class would need an additional `TParameter` argument which would further complicate the already convoluted class hierarchy and wouldn't be able to be shared with manual mixers since they have no thresholds.

Unfortunately, I don't think it's possible for me to fix those functions without redesigning the mixer transition classes and losing those benefits.

**Comment by LarsJandel** [comment]
Ah okay, thanks for the detailed explaination! 👍
I think, I understand the problem being separate arrays and the resulting behaviour.
No worries. 

User work-around: Move the candidate to duplicate to the bottom of the list first, then duplicate. 😉

**Comment by KybernetikGames** [comment]
I'll take another look at it when I get back to developing Animancer again. I probably can't do anything about those functions, but I could probably add a duplicate button down the bottom next to the `+` and `-` buttons. Or the `+` could duplicate the selected row instead of creating an empty element. Or maybe just do that when Right Clicked.

**Comment by LarsJandel** [comment]
Sounds good - thanks.
I was adding speed variations to the different 8-way locomotion directions, that's when the duplicate function comes in handy.

**Comment by KybernetikGames** [comment]
[Animancer v7.1](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-1) is now available:
- Changed the Add button in the Mixer Transition Inspector to duplicate the currently selected row instead of always adding at the end (unless you Right Click).
- Added an array size field to the footer.
I couldn't find a way to alter the inbuilt context menu functions.

**Comment by LarsJandel** [comment]
Thanks... ...wanted to give it a try. Not sure, if I did sth wrong: Deleted Animancer from within Unity, imported the update. It seems, the _Speed_ array moved visually down one entry in the UI. I can't click the `+` in this state unfortunately. Tried again via deleting Animancer when the project was closed and importing it when opened, but the same issue with the existing mixer. Thanks.

Screenshots: 1st initial, 
![image](https://user-images.githubusercontent.com/32457827/129355312-44706ef9-be45-4034-b095-87c578455421.png)
2nd when trying to click the `+` , which activated the _speed_ entry.
![image](https://user-images.githubusercontent.com/32457827/129355335-47802d24-fd71-494f-8e69-0189c741e41d.png)

**Comment by KybernetikGames** [comment]
Looks like an issue when the speeds are not all 1 so I missed it since the Directional Blending example has them all at 1 (which sets the actual array size to 0 and draws dummy fields for them instead).

I'll look into it tomorrow.

**Comment by KybernetikGames** [comment]
Apparently the way reorderable lists are drawn changed in a newer Unity version because the issue doesn't occur in 2019.4.

The proper fix needs a few fiddly changes around the place, but for a simple fix just go to `ManualMixerTransitionAsset.cs` (in *Utilities/Transitions*) line 65 and comment out the `[AnimationSpeed]` attribute above the `_Speeds` field.

**Comment by KybernetikGames** [comment]
I just re-released Animancer v7.1 with this issue fixed.

**Comment by LarsJandel** [comment]
Thanks for adding the duplicate functionality and the fix for newer Unity versions - working now!
🙏
