### ISSUE TITLE
Multiply blend mode for layers

### ISSUE THREAD

**Issue by WispBart** [KybernetikGames/animancer#142]
# Use Case

I want to use Animancer in combination with [Live2D Cubism](https://www.live2d.com/en/). A key workflow for Cubism is layering expressions on top of motions with multiplicative blending, which neither Mecanim nor Animancer currently support.

# Solution

A 'multiply' blend mode for layers in addition to additive and override.

# Alternatives

The Cubism for Unity SDK has an alternative workflow ('Original Workflow') to work around this issue, but that is currently incompatible with animancer and restrictive in other ways.

**Comment by WispBart** [comment]
I just noticed you're hooking into Unity / Mecanim's layer blending so this is probably not possible.

**Comment by KybernetikGames** [comment]
It's not possible using the inbuilt layer mixer, but if you really need it, it's probably possible using the Animation Jobs system. The [Animation Jobs Samples](https://github.com/Unity-Technologies/animation-jobs-samples) has a WeightedMaskMixer which you could adapt to multiply its inputs instead of using custom weights for each bone. Then you would need to modify the `AnimancerPlayable.LayerList` class to use your custom job instead of the default layer mixer. I've never done anything like that so I have no idea how hard it would be, but in theory it should work.
