### ISSUE TITLE
MixerStateTransition Preview issues(SRP)

### ISSUE THREAD

**Issue by thelebaron** [KybernetikGames/animancer#15]
Keeping this to one issue for now as I dont know how granular I should be with posting issues. 

1. In URP the material is pink. I haven't tried hdrp, but would assume the same if there's no special consideration for it.
2. Cannot pan the asset preview(ie if there is root motion, the model will just continue out of the bounds of viewable preview area). Or an option to have the camera follow the asset?
3. There is a IsGraphPlaying bool selection box that appears when the preview is paused, seems like an oversight? Not sure of its use if not.
4. Would be nice to have a grid to show the ground plane(or option to toggle one on).
5. Would also be nice if you could drag in other models to preview them using the transition setup but this is a very minor thing that I would also be fine not having.

Kybernetik Edit: changed bullet list to numbers.

**Comment by KybernetikGames** [comment]
Using individual issues is probably better so I can label and address them each on their own rather than leaving a big issue open just because only one of its points hasn't been addressed.

1. If you're referring to the transition preview material, I have no idea why it would do that since I'm just instantiating a copy of whatever model you are using and not touching anything about the material. I'll have to look into it. Which version of Unity are you using?
2. ... yep you sure can't. I don't use root motion much so I never even thought of it. I'll try to handle root motion like Unity's previews do.
3. The Is Graph Playing toggle is part of the regular `AnimancerComponent` Inspector that appears when the graph is paused (such as in the Doors example scene). I didn't want to waste space on it when it's unpaused because most of the time it won't be that useful so I only show it while paused. Any suggestions for how it should be handled?
4. Sounds like a good idea. Just another thing I didn't think of because I don't use root motion much.
5. You can already drag in other models, which was a necessary feature because it won't always be able to automatically find a model near the target transition in the Hierarchy (such as if you're using a transition asset).

**Comment by thelebaron** [comment]
1. Tested with Universal RP 7.1.7/7.1.6 & 19.3.0f3. Using 19.3.0f3 and builtin shows the model as normal. Brief test with HDRP 7.1.6 doesnt show anything in the window
3. I didn't notice that, just thought it was strange to see it on the preview window but that makes more sense now. 
5. Strange I thought this didn't work but I happily stand corrected.

**Comment by KybernetikGames** [comment]
I just released [Beta 6](https://kybernetikgames.github.io/animancer/v4-0/docs/changes/animancer-v4-0-beta/) which adds a ground grid to the preview window and handles root motion properly. The download link is the same as before.

I also split #1 into a [Separate Issue](https://github.com/KybernetikGames/animancer/issues/17) and reported it to Unity since it seems to be a bug in the `PreviewRenderUtility` class.

**Comment by KybernetikGames** [comment]
Just thought I'd let you know that the Scriptable Render Pipeline issues are now fixed in [Animancer v4.1](https://kybernetik.com.au/animancer/docs/changes/animancer-v4-1).
