### ISSUE TITLE
How to make something like OnStateUpdate from StateMachineBehaviour Scripts ?

### ISSUE THREAD

**Issue by DarkNemesisUmbrella** [KybernetikGames/animancer#153]
I'm using Animancer Lite and I'm trying to figure out on how to add events that get executed while a specific clip is playing.
I know I can make something like:

if(Animancer.IsPlaying(Clip))
{
          Function();
}

but I want a more elegant way like in the Events Examples :
Clip.Events.OnEnd += Function();
Is there something similar to this but while the clip es playing ?

**Comment by KybernetikGames** [comment]
There isn't anything built in to the animation system to do that because that sort of thing is usually better handled by the [State Machine](https://kybernetik.com.au/animancer/docs/manual/fsm/) system instead. States like the `LocomotionState` in the [Brains](https://kybernetik.com.au/animancer/docs/examples/fsm/brains/) example can simply have a regular `MonoBehaviour` `Update` method.

If you really do want to do it in the animation system, I can think of two possibilities:

- Make a class that implements [IUpdatable](https://kybernetik.com.au/animancer/api/Animancer/IUpdatable/) which checks if a specific clip is playing to call your function.
- Make a class that inherits from `ClipState`, override its `Update` method as necessary, and create an instance of that class to play your animation.

Note that both of those would require Animancer Pro. In Animancer Lite you'd basically have to use the code you posted in a regular `Update` method.
