### ISSUE TITLE
LinearMixerState incorrect speed when blending between 2 states

### ISSUE THREAD

**Issue by nehvaleem** [KybernetikGames/animancer#160]
# Environment

- Animancer Version Number:  7.2
- Animancer Pro or Lite: Pro
- Unity Version: 2020.3.18f1
- Platform: Windows

# Description

When blending between two states in LinearMixerState it seems that one of the animation is being speed up incorrectly when mid-blend (no state with weight 1). Video of the issue:  https://streamable.com/r0fvm9

It didn't happen on animancer 6.

# Reproduction

Steps to reproduce the bug:

1. Create LinearMixerState with 2 different animations
2. Set Parameter to something like 0.5;
3. See unnaturally speeded up animation

**Comment by KybernetikGames** [comment]
Most likely a bug in the mixer synchronization code. I'll look into it tonight.

**Comment by KybernetikGames** [comment]
I haven't been able to replicate the issue.

Do you see it in the [Linear Blending](https://kybernetik.com.au/animancer/docs/examples/locomotion/linear-blending/) example?

If not, can you show me your script?

**Comment by KybernetikGames** [comment]
This is by design because you have [Synchronization](https://kybernetik.com.au/animancer/docs/manual/blending/mixers/#synchronization) turned on for both animations in the mixer so it keeps their normalized times the same by altering their speeds.

So if you don't want them to do that, just disable the Sync toggle in the mixer transition.
