### ISSUE TITLE
Character getting stuck in state

### ISSUE THREAD

**Issue by ideletemyself** [KybernetikGames/animancer#166]
It's odd, it only happens when I hold certain key combinations for seemingly a certain amount of time. Say the W key and Spacebar which activates a RunningJump animation when the character is on the ground.

Or sometimes when I'm crouching and walking forward and then go into an idle crouch. It can happen with every state essentially but happens mostly with my Locomotion states and RunningJump states.

Is there an easy way to ensure a state completely ends or goes to the next state? Here's my code, I'm also using Unity's new input system:

`if (GetMovementInput() != default)
            {
                if (IsOnGround())
                {
                    GetComponent<CharacterMovement>().SetCapsuleHeight(2.0f);
                    SetMovementMode(MovementMode.Walking);
                    _Locomotion.TryEnterState();

                    if (_crouchButtonPressed)
                    {
                        GetComponent<CharacterMovement>().SetCapsuleHeight(1.75f);
                        SetMovementMode(MovementMode.Walking);
                        _CrouchWalkingState.TryEnterState();
                    }

                    if (IsSprinting())
                    {
                        GetComponent<CharacterMovement>().SetCapsuleHeight(2.0f);
                        SetMovementMode(MovementMode.Walking);
                        _RunToSprint.TryEnterState();
                    }

                    if (GetJumpInput() != default)
                    {
                        GetComponent<CharacterMovement>().SetCapsuleHeight(2.0f);
                        _RunningJump.TryEnterState();
                    }
                    else if (IsSprinting() && GetJumpInput() != default)
                    {
                        GetComponent<CharacterMovement>().SetCapsuleHeight(2.0f);
                        _RunningJump.TryEnterState();
                    }
                }
            }
            else if (GetMovementInput() == default)
            {
                if (IsOnGround())
                {
                    GetComponent<CharacterMovement>().SetCapsuleHeight(2.0f);
                    SetMovementMode(MovementMode.None);
                    _Character.Idle.TryEnterState();

                    if (_crouchButtonPressed)
                    {
                        GetComponent<CharacterMovement>().SetCapsuleHeight(1.5f);
                        SetMovementMode(MovementMode.None);
                        _CrouchIdleState.TryEnterState();
                    }

                    if (GetJumpInput() != default)
                    {
                        GetComponent<CharacterMovement>().SetCapsuleHeight(2.0f);
                        _Airborne.TryEnterState();
                    }
                }
            }`

**Comment by KybernetikGames** [comment]
The only way I can see for that code to stop doing any state changes would be if `IsOnGround()` starts returning false, so check that your ground detection system is working properly.

A couple of other comments:

- Modifying the character's physics shape shouldn't be done in the same method as input handling and most likely you only want to do it when the character actually enters the specified state, so you should put that logic in the states. Have your base state class specify the height it wants (using one of the approaches the [Interrupt Management](https://kybernetik.com.au/animancer/docs/examples/fsm/interrupts) example uses for action priorities) and apply it in `OnStateEnter`.
- Determining your current movement mode should likely be handled similarly.
- That would leave this method to just pick a state and try to enter it, which follows the Single Responsibility Principle much better.
- This bit makes no sense:

```
                if (GetJumpInput() != default)
                {
                    GetComponent<CharacterMovement>().SetCapsuleHeight(2.0f);
                    _RunningJump.TryEnterState();
                }
                else if (IsSprinting() && GetJumpInput() != default)
                {
                    GetComponent<CharacterMovement>().SetCapsuleHeight(2.0f);
                    _RunningJump.TryEnterState();
                }
```

Both blocks are identical and it can never get into the `else if` because if `&& GetJumpInput() != default` was true then it would have already gone into the `if` block above it.

**Comment by ideletemyself** [comment]
Ah that all makes sense. I had intended to move the capsule logic but got lazy. 

I’ll implement your recommendations and report my results when I get home tonight. 

Thanks again for your input. Really appreciate.

**Comment by ideletemyself** [comment]
So I've reorganized my code but have yet to implement the Action Types. I couldn't figure out how to access the Action Types Enum I just made in my base CharacterState class from my inherited states. Here's my code:

My base CharacterState:
![image](https://user-images.githubusercontent.com/2515465/139789483-f278d96c-c9e6-461f-aa26-2c5a58cba431.png)
![image](https://user-images.githubusercontent.com/2515465/139789519-5fe71528-7abb-4de0-8ac2-5a99677ba0d1.png)

My RunningJumpState:
![image](https://user-images.githubusercontent.com/2515465/139789574-62b5dd85-71ad-41cc-8e80-cf9a81665fbd.png)

I had stuff in the RunningJumpState but removed it for clarity since it was nonsense..

Also I added the Priority stuff to see if I could get that working and it does indeed work as intended.

And I guess I should add that moving the code around has so far removed the locked states for every state EXCEPT the RunningJumpState, which is why I'm showing that code specifically.

I'm pretty sure it's most likely due to the fact I'm not properly changing my states as you've stated above to do. If you could  show me how I'd go about doing that, generally, I'd surely appreciate.

**Comment by KybernetikGames** [comment]
Other classes will be able to access those enums as `CharacterState.Priority` and `CharacterState.CharacterActionType`.

None of the code you've shown looks like it would cause that behaviour. Try putting in some `Debug.Log`s to figure out what's actually getting called.

Also, you probably just want `Character.Animancer.Play(_Animation);` without the `0.25f` since it's a transition that can have its fade duration customized in the Inspector. You only need to specify it in code if you want to intentionally override the value set in the Inspector or if you're directly referencing an `AnimationClip`.

**Comment by ideletemyself** [comment]
Cool. Thanks again for all your assistance. 

Really loving Animancer!
