### ISSUE TITLE
Passing a Visual Effect object into a PlayableAssetTransition binding does not work when using a Visual Effects Activation track

### ISSUE THREAD

**Issue by mlaframboise** [KybernetikGames/animancer#170]
I am trying to play a VFX alongside a character animation inside a timeline.

I set the bindings for the animation track and the visual effects activation track as follows:
<img width="426" alt="Capture2" src="https://user-images.githubusercontent.com/7493782/142266854-37de32a8-9353-4272-9e16-e0605ba70670.PNG">

I left the first binding as null since according to the Animancer timeline documentation if the first track is an Animation track, it should not have a binding to the Animator directly.

The Timeline asset looks like this:
<img width="530" alt="Capture4" src="https://user-images.githubusercontent.com/7493782/142267452-cadccd33-4667-451a-9438-861a4e10a0e6.PNG">

The second binding is set to the VFX object in the scene, which looks like this:
<img width="435" alt="Capture3" src="https://user-images.githubusercontent.com/7493782/142267016-1a02b596-6f44-49ac-b195-e33b79a4c723.PNG">

However, when I play, I get the following errors in the console:
<img width="788" alt="Capture" src="https://user-images.githubusercontent.com/7493782/142267092-dcd9061d-e0ab-46c3-9c51-bc0a28f98613.PNG">

The character animation does play despite the error (I don't think the null check is working properly), but the VFX does not. It looks like the binding is only looking at the GameObject and not the attached Visual Effect component as expected.

If I create a PlayableDirector in the scene and manually set the bindings to the character animator and the VFX object, both play as expected.

**Comment by mlaframboise** [comment]
Reading the documentation, it looks like it should be possible to obtain a list of all the PlayableBindings for a PlayableAsset through PlayableAsset.outputs and then determine the expected type of each binding through PlayableBinding.outputTargetType. That would likely make things a lot more usable than the current Object array.

**Comment by KybernetikGames** [comment]
Are you using the latest version of Animancer (v7.2)?

It should be displaying the correct object type for each track:

![image](https://user-images.githubusercontent.com/43698611/142286308-98e007bf-0cf6-4dde-9880-4f85af69ece5.png)

For the first error, I suspect Unity has assigned a dummy object to the first element of the array rather than leaving it actually null. If you find where `PlayableAssetState` checks `!(binding is null)` and change it to `binding != null` it should fix the issue.

The second error is caused by the fact that the Inspector isn't showing the correct field type for each track so when you drag and drop a `GameObject` from the hierarchy, it can't automatically pick the correct component off it so it assigns the `GameObject` itself as the binding. You could work around that issue by using a second Inspector to drag and drop the actual `VisualEffect` component into the binding field like this:

![ComponentDrop](https://user-images.githubusercontent.com/43698611/142287784-fcbc82e5-a4e6-4fdb-a70d-bc4fa6560b88.gif)

But it would be better to figure out why the Inspector isn't drawing the fields correctly. If you go into `PlayableAssetTransitionAsset.cs` and put a `Debug.Log` in the `OnGUI` method, does it actually get called when you look at that transition in the Inspector?

**Comment by KybernetikGames** [comment]
Also, if you are using Odin Inspector, you'll need to update to the latest version of it because earlier ones break Animancer's transition drawers so that could be why it's not displaying correctly.

**Comment by mlaframboise** [comment]
It is was absolutely Odin inspector. Well, we were already talking about potentially replacing Odin anyway since we didn't want to upgrade to their subscription, but we definitely will be now.

Thanks!
