### ISSUE TITLE
Bug: MixerTransition2D Directional - Not blending at all.

### ISSUE THREAD

**Issue by jienma** [KybernetikGames/animancer#172]
Steps to reproduce:
Use MixerTransition2D with 8 animations for all directions ((1,1),(1,-1),(-1,1)...) without idle (no 0,0)
and they just don't transition between each other properly. They don't blend at all.
![image](https://user-images.githubusercontent.com/18059551/142746779-aff14688-4d79-468d-90e8-cac54837db0e.png)

* an important mention - even if you try to smooth the transition it just doesn't work.

**Comment by KybernetikGames** [comment]
Directional Mixers don't handle situations where there is a large angle difference between animations very well. Not having an Idle could potentially be a related problem so it's worth trying it with an Idle.

It's also worth trying with the Type set to Cartesian instead of Directional.

If neither of those helps, take a look at the `AnimancerComponent` Inspector to see how the weights are changing over time as you move the parameters.

**Comment by KybernetikGames** [comment]
Did that solve your issue?

**Comment by jienma** [comment]
Yes. Thank you.
