### ISSUE TITLE
animation speed will affect character final position and rotation

### ISSUE THREAD

**Issue by animebing** [KybernetikGames/animancer#175]
Thanks for your great work to simplify animation play. Recently I am using Animancer Pro to animate a character, I find that when I set  diffrent speed for the character to play, the final position and rotation(**more obvious**) are different. My play environment are listed below

- apply root motion
- transition from standing idle
- one is normal speed (the first image), the other is  2x speed (the second image)

![screen(4)](https://user-images.githubusercontent.com/19849456/144373175-34fed67c-9775-4908-9abf-f751806f209e.png)
![screen(5)](https://user-images.githubusercontent.com/19849456/144373201-6b9b9907-9cae-4334-8dac-2dde13d47819.png)
.

**Comment by KybernetikGames** [comment]
Is your `Animator` set to `Animate Physics` mode? Otherwise the motion will all be dependent on the frame rate, especially during the transition.

**Comment by animebing** [comment]
Thanks for your response, the `Update Mode` in `Animator` is set to `Normal` instead of` Animate Physics` and if I set it to `Animate Physics`, the phenomenon is almost the same. The `standing idle` and transition animation `Northern Soul Floor Combo` are listed in attaced zip file, please have a look, thanks

[animations.zip](https://github.com/KybernetikGames/animancer/files/7646688/animations.zip)

**Comment by KybernetikGames** [comment]
When I use `Animate Physics` mode I only get extremely small differences in root motion, which is what I'd expect due to floating point inaccuracy when playing the animations at differing speeds. But nothing like the massive differences you're seeing.

Can you make a minimal reproduction project and send it to animancer@kybernetik.com.au (or post it here with Animancer removed) so I can take a look at it?

**Comment by KybernetikGames** [comment]
I'm closing this issue since it seems to be inactive.
