### ISSUE TITLE
reverse animation by setting speed to be -1 is not working

### ISSUE THREAD

**Issue by animebing** [KybernetikGames/animancer#178]
I want to reverse an animation and I find a similar [issue](https://github.com/KybernetikGames/animancer/issues/137), according to that, I set the speed to be -1 when play the animation, but nothing happens, the animation is even not playing.

**Comment by KybernetikGames** [comment]
If your animation is not looping, you will also need to set the `state.NormalizedTime = 1;` so that it starts at the end and plays backwards from there. Otherwise it's playing backwards from the start and just getting clamped on the first frame.

If that doesn't help, take a look in the Inspector. Expand the state's details to see what speed/time/etc it has to see if you can identify the issue.

**Comment by animebing** [comment]
@KybernetikGames Thanks for your quick response, `state.NormalizedTime = 1;` works.
