### ISSUE TITLE
AnimationEvents get ignored during certain .Play() methods

### ISSUE THREAD

**Issue by NFMynster** [KybernetikGames/animancer#179]
Hello
First of all, thanks for the asset, seems super powerful, yet I got stuck with something I cannot find an answer to.
Searched all the issues on here also, I'm hoping you'll be able to guide me!

I can't seem to figure out why some of my animation events are getting ignored when passing along ClipTransitions in code?

My question is:
Why is it only `var state = AnimancerComponent.Layers[layer].Play(clipTransition);` that respects the ClipTransition's animation events?

My setup:
1. I have a blendtree (MixerTransition2D) which is running by "default".
![image](https://user-images.githubusercontent.com/5054730/147011534-c3a53123-a1ff-48c4-b30a-ed8d4d0e937e.png)
2. I now want to play another animation, on another layer. 
![image](https://user-images.githubusercontent.com/5054730/147011751-7151eaf1-dc8a-4092-a35d-259b0d03a684.png)

I've tried several approaches but simply cannot get it just right.
This is what I've tried so far:
![image](https://user-images.githubusercontent.com/5054730/147012374-5d75c020-d28b-44d0-8506-d6f993091410.png)

**Comment by KybernetikGames** [comment]
Events are removed from a state whenever it gets stopped in case you have multiple different things using the same `AnimationClip` and therefore sharing the same `AnimancerState`. The [Clear Automatically](https://kybernetik.com.au/animancer/docs/manual/events/animancer/behaviour#clear-automatically) section explains how and why it works like that.

Similarly, states have no idea about fade durations because multiple transitions could share the same state with different values so playing or stopping a state can't cause it to fade. If you want to use the fade/events/etc of a transition, you need to play that transition.

In this case, rather than stopping the state, you likely want to fade out the layer it's on like in the [Layers](https://kybernetik.com.au/animancer/docs/examples/layers/) example. If you want that fade out to use the fade duration defined in the mixer's transition, you can simply give it `movementBlendTree.FadeDuration` as the duration.

Also, the `GetOrCreate` and `Evaluate` in your `Awake` method are likely unnecessary.

**Comment by NFMynster** [comment]
Oh, well, yes, okay, I see how I need to use the other Play overload, thank you. Now the animation event is invoked.
I noticed this a few times also.

My setup from converting from Mechanim to Animancer, includes pausing an animation midway as you're "charging/priming" a throwable spear.
I am setting the state to "IsPlaying = false" in the animation event and then later to true again.

``` var throwState = playerAnimator.AnimancerComponent.Layers[1].GetOrCreateState(attackAnimation);
            throwState .IsPlaying = false;```

https://streamable.com/prk0q7

It seems like a microstutter is happening whenever the event is invoked, as you can see on the video I posted.
Do you seem to have any idea why?
If I don't pause the animation, no stutter appears.

**Comment by KybernetikGames** [comment]
I can't think of any reason why that would happen.

Try pausing Unity and stepping through frame by frame with the object selected so you can see its Inspector. Maybe you'll be able to spot something wrong there.

Otherwise, if you make a minimal reproduction project and send it to animancer@kybernetik.com.au I'll see if I can figure out what's happening.

**Comment by NFMynster** [comment]
Alright,  I believe it was some timings on my animation event. Ie, if I've set the animation event time to a specific timestamp and then replace the animation clip.

Anyways, resetting inspector fixed this (I think haha), so closing the issue for now!

Thanks for the support and sorry for the late reply.
