### ISSUE TITLE
First frame is played of first animation when starting second animation

### ISSUE THREAD

**Issue by Ashnu11** [KybernetikGames/animancer#180]
# Environment

- Animancer Version Number:
- 7.2
- Animancer Pro or Lite: 
- pro
- Unity Version: 
- 2020.3.17
- Platform: 
-windows
# Description
First frame is played of first animation when starting second animation

# Reproduction

Steps to reproduce the bug:

1.
```
if (Input.GetKeyDown(KeyCode.J))
        {
            var clip1= GetAnimationClip(CharacterAni.DefendStart);
            var clip2 = GetAnimationClip(CharacterAni.Defending);
            Animancer.Play(clip1, 0).Events.OnEnd += () =>
            {
                Animancer.Play(clip2);
            }; 
```
2. Enter Play Mode

**Comment by KybernetikGames** [comment]
Is your `DefendStart` animation looping? Because events only occur when the state time has actually passed the event time so it would loop back to near the start before the newly played animation is actually able to take effect.

Otherwise, I haven't been able to replicate the issue so could you email a minimal reproduction project to animancer@kybernetik.com.au so I can take a look at your exact setup?

**Comment by Ashnu11** [comment]
> 

I solved the problem by canceling the loop.<3
