### ISSUE TITLE
OnEnd event handler has inconsistent behavior

### ISSUE THREAD

**Issue by Aezoc** [KybernetikGames/animancer#188]
# Environment

- Animancer Version Number: 7.2
- Animancer Pro or Lite: Pro
- Unity Version: 2021.2.11f
- Platform: Win10

# Description
OnEnd event handler behavior appears to differ depending on whether other events are also defined. I would expect that other events do not affect the behavior, and could not find documentation that said otherwise.

# Reproduction

Steps to reproduce the bug:

Attach a component like this to an animated character. Assign any short animation asset to its field. If the clip has no events defined in the inspector, the end event will only fire the first time the clip plays. If you add a dummy event to the clip, the end event will fire every time.
```C#
    public class UnsharedEventsTest : MonoBehaviour
    {
        [SerializeField] private ClipTransitionAsset.UnShared _clip;

        private AnimancerComponent _animancer;

        private void Start()
        {
            _animancer = GetComponent<AnimancerComponent>();
            var state = _animancer.Play(_clip);
            state.Events.OnEnd = () =>
            {
                state.Stop();
                Debug.Log("Clip ended");
            };
            StartCoroutine(PlayRepeatedly());
        }

        private IEnumerator PlayRepeatedly()
        {
            while (true)
            {
                yield return new WaitForSeconds(3f);
                _animancer.Play(_clip);
            }
        }
    }
```

**Comment by KybernetikGames** [comment]
The problem relates to the way events are [Cleared Automatically](https://kybernetik.com.au/animancer/docs/manual/events/animancer/behaviour#clear-automatically) when you stop the state.

- When your transition has no events, it assigns no `AnimancerEvent.Sequence` to the state it plays.
  - Then you add an event to the state, causing it to get a spare event sequence from the object pool to put your event in.
  - Because that event sequence was retrieved from the object pool, when the state is stopped it clears the event sequence and returns it to the pool.
  - Now your event is now gone and nothing is adding it again.
- When your transition has events (regular events or an end event or even just an adjusted end time), playing it will assign those events to the state.
  - Then you add an event to the state, which is using the event sequence given to it by the transition.
  - Because that event sequence is owned by the transition instead of coming from the object pool, stopping the state doesn't clear the event sequence or return it to the object pool, it just gets removed from the state.
  - Then when you play the transition again, it still has its event sequence which still has your event in it.

The solution is to just add your events to the transition before playing it (you should always do this when using transitions):

```
    private void Start()
    {
        _clip.Events.OnEnd = () =>
        {
            _clip.State.Stop();
            // Or: AnimancerEvent.CurrentState.Stop();
            Debug.Log("Clip ended");
        };

        _animancer = GetComponent<AnimancerComponent>();
        _animancer.Play(_clip);
        StartCoroutine(PlayRepeatedly());
    }
```

I'd like to be able to detect issues like this automatically to log a warning, but unfortunately I haven't come up with a viable way to do so without compromising performance.
