### ISSUE TITLE
No Video Tutorials - Improvement to GIFs

### ISSUE THREAD

**Issue by baroquedub** [KybernetikGames/animancer#190]
Just to add to the debate about "No Video Tutorials" :)

I totally get where you're coming from, although I would personally much prefer a few hand-holding walkthroughs to get my head around the basics. (I might get around to doing one or two when I start to understand Animancer). At the moment I'm getting a bit of a feeling of information overload, just from the amount of text, code, sheer number of pages in the docs. (I'm sure I'll be glad of all that detail in good time)
The one request I would make - to mitigate against the visual noise that the animated GIFs add to - is to add an option to pause each GIF. As per this CSS code snippet: [https://css-tricks.com/pause-gif-details-summary/](https://css-tricks.com/pause-gif-details-summary/) It would make a world of difference and make the docs a lot more approachable.

**Comment by KybernetikGames** [comment]
The [Quick Play](https://kybernetik.com.au/animancer/docs/examples/basics/quick-play/) example already does go into extreme hand-holding detail with explanations of things outside of Animancer like how to set up a scene, how to make a new script, and links to my other documentation about [Composition](https://kybernetik.com.au/cs-unity/docs/introduction/inheritance#composition), [Serialized Fields](https://kybernetik.com.au/cs-unity/docs/introduction/variables/#serialized-fields), and [Namespaces](https://kybernetik.com.au/cs-unity/docs/introduction/organization/#namespaces).

So all the information you should need is there, but I totally see what you're saying about information overload and the overall length of the page. I've actually had similar feedback from a few other people and I'm currently in the process of splitting that example into 4 much smaller ones:

1. Just use a script to play an *Idle* animation.
2. Swap between *Idle* and *Walk* based on keyboard input.
3. Play an action animation when you click and use an [End Event](https://kybernetik.com.au/animancer/docs/manual/events/end/) to return to *Idle* afterwards.
4. Combine number 2 and 3 into one script. I'm not really sure about this one since it doesn't actually teach anything new about Animancer, but I suspect beginner programmers would find it useful.

If you have any similar feedback about specific parts of the documentation, please do let me know because my perspective as an experienced programmer and author of the system is very different from new users and beginner programmers.

Pausing the gifs is a good idea, but needing to individually save out the first frame and set up that code snippet for every gif (there are currently 203 in the whole documentation) sounds extremely painful and annoying to maintain in the future whenever I make changes. I tried using [FreezeFrame](https://github.com/ctrl-freaks/freezeframe.js) a while ago, but couldn't get it working in Wyam (the static site generator I use) and I'm not a web developer so I had no real idea what I was doing or how to debug the problem. But I'll put it on my to do list to have another go at it sometime after I release this Animancer update.

**Comment by baroquedub** [comment]
Thanks for the quick response. Thing is, I'm actually an intermediate programmer so my problem isn't understanding the basics but more trying to get my head around how I can use Animancer in my own game. The hand holding I'm talking about isn't a simple beginner tutorial but a real-world implementation. It's perhaps that the Quick play is too simple while the later pages like Transitions (which I'm guessing is actually what I'll need to be using) is just outside of what I can currently grasp. I've owned the asset for a while but never used it as that initial transition into its way of thinking has seemed a little too obtuse to me. (It reminds me a little about how I felt about DOTween before I grasped its concept of Tweens and Sequences). It was reading the recent review by protopop (I'm a big fan of his) that made me decide to finally take the plunge and learn to use Animancer - that and your comments about being willing to look into the Animation Jobs system for weighted mask mixers https://forum.unity.com/threads/still-no-way-to-get-fine-grained-masking-with-humanoid-animations.385964/#post-6615871 but that's for another ticket :)

**Comment by KybernetikGames** [comment]
# Examples

[Animancer v7.3](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-3/) is now available, which includes a massive rework of most examples. In particular, the [Basics](https://kybernetik.com.au/animancer/docs/examples/basics/) are simpler and the [State Machines](https://kybernetik.com.au/animancer/docs/examples/fsm/) examples are more straightforward because they avoid irrelevant implementation details that needed explaining (raycasting, playing audio, moving the camera, etc.). So by the end of [Weapons](https://kybernetik.com.au/animancer/docs/examples/fsm/weapons/) (which now includes an actual scene) you have a character that can walk, run, equip weapons, and attack with them, which should be a good starting point for a character in a real game.

# Gif Pausing

I've also spent a few days on the gif pausing issue and made some good progress.

## Saving First Frame

[I found a simple way to save the frames of a gif as pngs in code](https://stackoverflow.com/a/36023146), so I just made it do only the first frame and to recursively find all gifs in a directory to save their png next to them. It uses *System.Drawing.dll* and I couldn't figure out how to get Unity to import it so I had to make it a separate console application, but that's fine.

## Details / Summary

<p><details><summary>I got the details/summary idea working with these styles:</summary>

```
.pausable {
  display: inline-block;
  position: relative;
}

.pausable summary {
  width:  100%;
  height: 100%;
  position: absolute;
  top: 0px;
  right: 0px;
  z-index: 2;
}

.pausable details img {
  display: inline-block;
  position: absolute;
  top: 0px;
  left: 0px;
}

/* for firefox */
.pausable details > summary:first-of-type {
  list-style: none;
}

/* for blink/webkit */
details summary::-webkit-details-marker {
  display: none;
}
```
</details></p>

It did the job, but this is far too much to write and maintain for every gif:

```
<div class="pausable">
  <img src="Test.png" loading="lazy">
  <details>
    <summary role="button"></summary>
    <img src="Test.gif" loading="lazy">
  </details>
</div>
```

## Javascript

So I went back to looking at javascript approaches. I still couldn't get FreezeFrame (or any similar library I tried) to work, but I finally managed to implement some simple javascript to do it myself

<p><details><summary>The script looks like this:</summary>

```
const collection = document.getElementsByClassName("png-gif");
for (let i = 0; i < collection.length; i++) {
  var item = collection[i];
  item.setAttribute("onclick", "ImgClicked1(this);");
  item.onclick = ImgClicked0;
}

function ImgClicked1(item) {
  var src = item.getAttribute("src");
  var name = src.slice(0, -3);
  if (src[src.length - 1] == "g")
    name += "gif";
  else
    name += "png";
  item.setAttribute("src", name);
}

function ImgClicked0() { ImgClicked1(item); }
```
</details></p>

Which means I only need this for each gif:

```
<img src="thing.png" class="png-gif">
```

## What Now?

I have the Play/Pause working, but I'm not sure exactly what behaviour would be best ([FreezeFrame has some examples](https://ctrl-freaks.github.io/freezeframe.js/)):

- Should they be playing or paused by default?
- Click to play/pause or mouse hover to play?
  - Click to play/pause would mean images can't be used as links (all the images on the [home page](https://kybernetik.com.au/animancer) are links, but they don't necessarily need to be).
- Should I use it on all gifs?
  - For example, hover to play would be annoying when there are two gifs side by side for comparison like in the [Mixer Synchronization](https://kybernetik.com.au/animancer/docs/manual/blending/mixers/#synchronization) section.
- Should it display play/pause icons?
  - I could make the first frame extractor add a play button overlay before saving the png.
  - Adding a pause icon on the gif would make the script much more complicated, but should be doable (I think).
- It might be possible to add a dedicated play/pause button up in the corner of the image, which should also solve the issue with "click to play/pause" preventing gifs from being used as links.
  - That means I'd need to make sure never to have important stuff in that corner or any gif. Unless I can also make that button only show up on hover?

Thoughts?

**Comment by baroquedub** [comment]
Here's my two pennies:

Gifs should play on default (ideally only when 'in view' (see: https://www.javascripttutorial.net/dom/css/check-if-an-element-is-visible-in-the-viewport/) as there's no point in a gif below the fold (out of view) from playing.

Then show a replay icon overlay.

In cases where two gifs are side by side (for comparison of features) The replay (play) functionality should activate both gifs.

Activating play should not be done onMouseOver but onClick.

Gifs should not loop but only play to their end then stop. (You might consider a small 'loop' icon in the corner of each gif so users can choose to toggle on loop mode, but that's probably overkill).
- the main issue for me was always visual noise (everything moving all the time). Actively choosing to play a gif (clicking play to see what I'm trying to learn is far better than watching something continuously running). That repetition of having to click play again may feel repetitive but it's actually useful in making the learner actively engage with the information being displayed.

**Comment by KybernetikGames** [comment]
> Gifs should play on default (ideally only when 'in view'

If they start playing when they first come on screen, that means you'll miss the start of every gif since it will still be half off screen. And that conflicts with your later idea because if they also don't loop, then the first play through is basically pointless so they'd be better paused by default.

Maybe I could wait until the whole thing is on screen, but having a large gif suddenly start playing when it was already showing a play button just because you scrolled a bit seems like a bad idea.

> In cases where two gifs are side by side (for comparison of features) The replay (play) functionality should activate both gifs.

That would also ensure that both gifs are in sync (they often get out of sync over time even if they have the same length). The actual implementation would likely be a bit tricky, but should be doable.

> You might consider a small 'loop' icon in the corner of each gif so users can choose to toggle on loop mode

That would need a significantly more complicated library because the loop flag is part of the gif file (I think its actually a loop counter), not controllable from html or javascript.

> Actively choosing to play a gif (clicking play to see what I'm trying to learn is far better than watching something continuously running). That repetition of having to click play again may feel repetitive but it's actually useful in making the learner actively engage with the information being displayed.

That makes a lot of sense.

You go to the [Quick Play](https://kybernetik.com.au/animancer/docs/examples/basics/quick-play/) example and should start reading the Learning Outcomes and introduction, but your eye will be drawn to this big gif that you can only see half of, so you scroll down to see what that's about and now you've missed the start so you have to wait for the 30 second long loop and try go get your bearings at the start before stuff starts happening again.

On a side note, do you think 30 seconds is too long (especially for the first example)? Maybe I should split it into "setting up the components" and "here's what it looks like actually playing".

![image](https://user-images.githubusercontent.com/43698611/178088736-effd7d63-6448-4b60-9895-8a84adba6c61.png)

Or you go to the [Home Page](https://kybernetik.com.au/animancer/) and your eye is again drawn down to the only moving thing which you can only see half of. The idea I was going for was basically "hey look at this cool stuff Animancer can do, I bet you want to read the rest of this page now", but that's probably silly because it's basically trying to advertise the page you're already on.

![image](https://user-images.githubusercontent.com/43698611/178088909-d47a32c6-c8ce-4c9f-8903-c487dbd978ba.png)

And yeah, there's a lot of visual noise in some places where you have 3 gifs on screen at once (maybe more if you have a large monitor).

![image](https://user-images.githubusercontent.com/43698611/178088850-13e68b9b-aac3-4569-a44b-8e7fccc51a3e.png)

I don't think turning off looping would provide a good user experience though:
- Stopped on First Frame -> Click to Play -> Watch it play -> Gif Pauses at the end -> Click to Stop -> Click to Play again.
- Being able to take your time to examine the last frame might be nice, but needing two clicks to restart would be bad.
- I could probably make it one click to restart, but there's no way for me to check if it's done so that would replace Click to Stop, meaning you'd have to wait for it to finish if you want it to stop being distracting.

So I'm leaning towards:

- Stop by default to reduce distractions and deliver information when the user is actually ready for it. This is also better for page load times since the gifs would naturally be lazy loaded.
- Click to play / stop.
- Show a play icon while stopped (baked into the first frame png) but no stop button while playing.
- Stick with automatically looping gifs.

**Comment by RustedGames** [comment]
Personally I don't find the way it is right now annoying, but Click to Play sounds a better option indeed ;)

**Comment by KybernetikGames** [comment]
Stoppable gifs are now live.

I found that once it was no longer running locally there would be a notable delay the first time you play the gif, so I made the script pre-load the gifs which seems to work well.

```
const collection = document.getElementsByClassName("pngif");
var gifs = [];
for (let i = 0; i < collection.length; i++) {
  var item = collection[i];
  item.setAttribute("onclick", "pngif(this);");

  var src = item.getAttribute("src");
  src = src.slice(0, -3) + "gif";
  gifs[i] = new Image();
  gifs[i].src = src;
}

function pngif(item) {
  var src = item.getAttribute("src");
  var name = src.slice(0, -3);
  if (src[src.length - 1] == "g")
    name += "gif";
  else
    name += "png";
  item.setAttribute("src", name);
}
```
