### ISSUE TITLE
Is it possible to play a timeline with override tracks? 

### ISSUE THREAD

**Issue by ph3rin** [KybernetikGames/animancer#191]
Unity version: 2021.2.6f1 | Animancer version: 7.2

Hi,

I used the Animancer component to play animation on my character. However, sometimes I would like to play animations via a timeline. Now I have a timeline with a base animation track and an override track. The override track has an avatar mask (in the example below, the `Upper Body` avatar mask provided in Animancer's examples). I am expecting the timeline to play the base track's animation clip (which is `Humanoid Walking` in the example below) but the upper body would be controlled by the override track.

With Unity's built in playable director (by calling `PlayableDirectior.Play()`), I get the result I expect:

![timeline_anim_mute_override](https://user-images.githubusercontent.com/35837496/154827243-f163c853-4c87-4c44-bb5e-66d04fcf6df9.gif)

<p align="center">Play with PlayableDirector, with override track **muted**</p>

![timeline_anim](https://user-images.githubusercontent.com/35837496/154827312-513fdc42-ece9-447f-a7c5-360772b099d3.gif)

<p align="center">Play with PlayableDirector, with override track **unmuted**</p>

However, you'll notice that the animation does not fade in but instead directly replaced the idle animation.

However, if I instead use `animancer.Play(playableAssetTransition)`, I get the cross fading I want, but the character goes into the crouch state when I call `Play`, unless I mute the override track:

![animancer_timeline](https://user-images.githubusercontent.com/35837496/154827661-0b99fb1c-627f-42e8-8d7f-21f33dbcc063.gif)

<p align="center">Play with Animancer, with override track **unmuted**</p>

A possible workaround I can think of is to create the two animation tracks in two different timelines, and to play those two timelines on different layers (and set the avatar masks on the layers). However, this makes previewing the timeline while editing harder. Is there a better way to do this?

**Comment by KybernetikGames** [comment]
This sounds like it relates to the 2nd and 3rd dot points in the [Bindings](https://kybernetik.com.au/animancer/docs/manual/timeline/#bindings) section.

- The output of the first animation track automatically gets fed into Animancer like a regular state, but others will need to be given a specific `Animator` to control.
- And if you bind the `Animator` that Animancer is using, it will take control away from Animancer and not give it back afterwards.

Unfortunately, I don't think there's anything Animancer can do about it. Timeline wasn't really written with the intent of being used in a custom Playable Graph so things like this often either work as intended straight away or won't work at all and have no workaround (other than editing Timeline itself which you could theoretically do because you have access to its source code).

**Comment by KybernetikGames** [comment]
[Animancer v7.3](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-3) is now out and has a few improvements to the Timeline integration, but unfortunately I never managed to find a way to fix this particular problem.

For now I'll close this issue due to lack of activity. Feel free to re-open if you have any new information.
