### ISSUE TITLE
Animancer Error When Importing PSB File Using Unity’s PSD Importer

### ISSUE THREAD

**Issue by Unrighteous** [KybernetikGames/animancer#194]
# Environment

- Animancer Version Number: 7.2
- Animancer Pro or Lite: Pro
- Unity Version: 2020.3.30f1
- Platform: Windows 10

# Description

I receive multiple of the same error when importing a PSB file into my project, and the errors reappear in the console whenever I make changes to the PSB file.

# Reproduction

1. Create a project using Unity's 2D Core template.
2. Import Animancer.
3. Import a PSB file.
4. Observe the errors.

![Errors](https://user-images.githubusercontent.com/101363476/157749971-c28da82f-25a1-4847-bb16-612d9e057b00.PNG)

The errors don't seem to be causing any issues. This is the first time I've seen this happen.

**Comment by KybernetikGames** [comment]
I've already fixed this issue but from what I can remember it's a bit too complex to explain which lines to change here so if you send your Invoice Number to animancer@kybernetik.com.au I'll send you the fixed `SpriteEditor.cs` file.

It will also be fixed in the next version of Animancer (which is probably still at least a few weeks away).

**Comment by KybernetikGames** [comment]
[Animancer v7.3](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-3/) is now available and has this fix in it.
