### ISSUE TITLE
The second time an animation clip is played, it enters this animation state with a delay of one frame.

### ISSUE THREAD

**Issue by StraussDurant** [KybernetikGames/animancer#197]
# Environment

- Animancer Version Number: 7.2
- Animancer Pro or Lite: pro
- Unity Version: 2020.2.6f1
- Platform: Editor

# Description

The second time an animation clip is played, it enters this animation state with a delay of one frame.

# Reproduction

Steps to reproduce the bug:
1. Go to Examples/01 Basics/02 Playing And Fading
2.Open PlayingAndFading.cs
(1).Annotate the OnEnable function and don't let the Idle clip be played when the DefaultHumanoid is initialized
```
//private void OnEnable()
//{
    //_Animancer.Play(_Idle);
//}
```
(2).Change the PlayThenIdle Function Like This
```
_Animancer.Play(_Action).Events.OnEnd = () =>
{
    _Animancer.Play(_Idle);
    EditorApplication.isPaused = true;
};
```
3. Enter Play Mode And Click PlayThenIdle
**(First Play Clip)**
When the editor is paused,click step.
![1647939116(1)](https://user-images.githubusercontent.com/19651150/159442889-162024d1-1481-4122-85c9-61e8e381b967.jpg)
Then, we observe AnimancerComponent and it have entered the Idle Animation state. It's perfect.
![image](https://user-images.githubusercontent.com/19651150/159443688-3c472d91-f001-437b-915f-3d471c7cf174.png)
**(Second times Play Clip)**
Release the pause.
![image](https://user-images.githubusercontent.com/19651150/159443874-22b7d57f-141c-4197-be6a-e6eb7723611b.png)
Click PlayThenIdle again.
When the editor is paused,click step.
Then, we observe AnimancerComponent and this time the Idle animation is not started.
![image](https://user-images.githubusercontent.com/19651150/159444307-8feaa2aa-800d-492c-8630-885d84fbcf20.png)
Until I click Step again, the character enters the Idle animation state.
![image](https://user-images.githubusercontent.com/19651150/159444433-a7651907-0cdd-4414-8f11-218f946f8578.png)

**Comment by KybernetikGames** [comment]
Unfortunately, this behaviour is entirely controlled by the Playables API and I don't think there's anything Animancer can do about it.

When you call `SetTime` on a `Playable`, the next animation update will apply it at that value and leave it there, then on the next update after that it will advance again.

The problem is that it doesn't count frames where the animation isn't playing so when Animancer stops something and resets it to 0, the "next frame" where it applies at 0 time is actually the first frame when it starts playing again.

So you get this:

1. Play action.
2. Action ends, play idle and pause.
3. It hasn't updated in the idle animation yet so it's still in the action end pose even though the Inspector is showing the Weight 1 on the idle state.
4. Step one frame.
5. Time advanced because it's new and it's now a little into the idle animation. It never showed the idle at Time = 0.
6. Play action.
7. Action ends, play idle and pause.
8. It hasn't updated in the idle animation yet so it's still in the action end pose even though the Inspector is showing the Weight 1 on the idle state.
9. Step one frame.
10. That was the first update that idle received since its time was set to 0 so its time is still at 0 and it's now in the idle pose.
11. Step one frame.
12. Now time advances again.

I'll report it as a Unity bug, but most likely they'll just claim it's "by design" (and even if they do fix it, it likely won't be any time soon).

**Comment by StraussDurant** [comment]
> Unfortunately, this behaviour is entirely controlled by the Playables API and I don't think there's anything Animancer can do about it.
> 
> When you call `SetTime` on a `Playable`, the next animation update will apply it at that value and leave it there, then on the next update after that it will advance again.
> 
> The problem is that it doesn't count frames where the animation isn't playing so when Animancer stops something and resets it to 0, the "next frame" where it applies at 0 time is actually the first frame when it starts playing again.
> 
> So you get this:
> 
> 1. Play action.
> 2. Action ends, play idle and pause.
> 3. It hasn't updated in the idle animation yet so it's still in the action end pose even though the Inspector is showing the Weight 1 on the idle state.
> 4. Step one frame.
> 5. Time advanced because it's new and it's now a little into the idle animation. It never showed the idle at Time = 0.
> 6. Play action.
> 7. Action ends, play idle and pause.
> 8. It hasn't updated in the idle animation yet so it's still in the action end pose even though the Inspector is showing the Weight 1 on the idle state.
> 9. Step one frame.
> 10. That was the first update that idle received since its time was set to 0 so its time is still at 0 and it's now in the idle pose.
> 11. Step one frame.
> 12. Now time advances again.
> 
> I'll report it as a Unity bug, but most likely they'll just claim it's "by design" (and even if they do fix it, it likely won't be any time soon).

Thank you very much.I'm wondering if I can avoid this error by recreating the Playable every time a new clip is played, is there any hidden danger?
Because when I use RootMotion, the one frame that stops makes my displacement drop one frame. If I use camera damping, it causes the character to jitter. So I need to fix it.

**Comment by KybernetikGames** [comment]
`state.RecreatePlayable();` should do it, and aside from the obvious performance cost (which might not be too bad) I don't think there should be any hidden dangers.

I started making a bug report and found that Animator Controllers actually give the same behaviour, so there's not going to be any point in finishing and submitting the report because they won't consider it a bug.

**Comment by StraussDurant** [comment]
> `state.RecreatePlayable();` should do it, and aside from the obvious performance cost (which might not be too bad) I don't think there should be any hidden dangers.
> 
> I started making a bug report and found that Animator Controllers actually give the same behaviour, so there's not going to be any point in finishing and submitting the report because they won't consider it a bug.

OK,ThankYou! I'm will try to use state.RecreatePlayable(); to fix it.
I tried running the same behaviour in Unreal and Unreal gave perfect performance. Hopefully Unity will take care of it and fix it in the future

**Comment by StraussDurant** [comment]
> `state.RecreatePlayable();` should do it, and aside from the obvious performance cost (which might not be too bad) I don't think there should be any hidden dangers.
> 
> I started making a bug report and found that Animator Controllers actually give the same behaviour, so there's not going to be any point in finishing and submitting the report because they won't consider it a bug.

Sorry, I call the RecreatePlayable method in the “Play”Function of AnimancerState. 
![image](https://user-images.githubusercontent.com/19651150/159482197-31fe3008-a432-40d1-bc9d-6de602535a13.png)
It is valid for AnimationClip, but when I play a MixerState, it will not play correctly, do you have better suggestions for me to avoid this bug or reasonable where to call RecreatePlayable?

**Comment by KybernetikGames** [comment]
If you need to support mixers there's a `RecreatePlayableRecursive` that will apply to the child states as well.

Also, note that the `AnimancerState.Play` method is only used if you are playing the animation without a fade. If you're using fading, you'll probably want to put the call in the `AnimancerLayer.Play` method that takes a `fadeDuration` parameter.

**Comment by StraussDurant** [comment]
> If you need to support mixers there's a `RecreatePlayableRecursive` that will apply to the child states as well.
> 
> Also, note that the `AnimancerState.Play` method is only used if you are playing the animation without a fade. If you're using fading, you'll probably want to put the call in the `AnimancerLayer.Play` method that takes a `fadeDuration` parameter.

OK, I understand.You help me a lot.Thank You
