### ISSUE TITLE
How to manage animation events without Animancer transitions?

### ISSUE THREAD

**Issue by levidavidmurray** [KybernetikGames/animancer#198]
I have 5 attack animations that I'm chaining together for combos. I originally had the animations as individual `AnimationClip`'s that I was passing into `AnimancerComponent::Play`. I also had regular animation events (`AttackTrailStart` and `AttackTrailStop`) attached to each animation.
![image](https://user-images.githubusercontent.com/46084870/159826764-b88cd0ba-fd42-4c3c-a26f-acc60f93ada6.png)

I thought it'd be easier to manage the animations within my `AttackState` itself, rather than passing it through the `PlayerBehaviour` object (my states are not `MonoBehaviour`'s). I quickly found out that this wouldn't work: 
```csharp
    _AnimState = Instance.Animancer.Play(animData.Clip, _FadeSpeed);
    _AnimState.Speed = animData.Speed;
    
    _AnimState.Events.OnEnd = () => {
        StateMachine.TrySetState(Instance._IdleState);
    };

    if (!_IsInitialized) {
        _AnimState.Events.SetCallback("AttackTrailStart", () => {
            print($"AttackTrailStart!");
        });

        _AnimState.Events.SetCallback("AttackTrailStop", () => {
            print($"AttackTrailStop!"); 
        });
        
        _IsInitialized = true;
    }
```
It complained about `AttackTrailStart` and `AttackTrailStop` events not existing. So I assumed I can't listen for regular Unity animation events via Animancer, and I couldn't find anything in the documentation regarding this. Okay, I guess I'll make it a Mixer and add the events there. But I ran into a couple issues:

1. I can't figure out how to create events for individual animations in the Mixer (rather than creating it on the normalized time for the entire Mixer).
2. Calling `LinearMixerTransition::Play` again and changing the parameter (`LinearMixerTransition::State::Parameter`) doesn't do anything because (I assume) the animations aren't set to loop (I don't want the animations to loop, but I do want to be able to recall the Mixer animation for the next attack animation in the chain).
3. I tried setting `AnimancerState::Time` to `0`, and this _kind of_ does what I want. But it doesn't blend with the previous animation.
![image](https://user-images.githubusercontent.com/46084870/159833987-b2ddbb91-5488-4fc7-acbe-69ce6b897b38.png)
```csharp
private void HandleAttack() {
    Instance.InputHandler.UseAttackLightInput();
    _AttackAnim.State.Parameter = _AttackAnimIndex;
    _AnimState = Instance.Animancer.Play(_AttackAnim, _FadeSpeed);
    _AnimState.Time = 0;
        
    _AnimState.Events.OnEnd = () => {
        StateMachine.TrySetState(Instance._IdleState);
    };
}
```

**Questions:**
1. Can you listen for regular Unity animation events that are attached to an `AnimationClip` when passing the clip into `AnimancerComponent::Play`?
2. Can you create events per animation within the Mixer?
3. How should I chain these attack animations if I want them to blend nicely?

**Comment by KybernetikGames** [comment]
> I can't listen for regular Unity animation events via Animancer

That's correct, the two systems are entirely separate. The [Events](https://kybernetik.com.au/animancer/docs/manual/events/) page explains their differences.

Though there is an `Animator.fireEvents` property that should disable Animation Events and an `AnimationClip.events` property that would let Animancer grab all the event times and names to create Animancer Events from them. That would let you set up Animation Events in the Animation window and then assign the callbacks in code. So it should be possible for me to implement, but I likely won't be able to make it fully automatic because that would cost some performance for everyone even if they don't use it.

> I thought it'd be easier to manage the animations within my AttackState itself, rather than passing it through the PlayerBehaviour object (my states are not MonoBehaviour's). I quickly found out that this wouldn't work

The way you're using `_IsInitialized` won't work because Animancer Events are [Cleared Automatically](https://kybernetik.com.au/animancer/docs/manual/events/animancer/behaviour#clear-automatically) whenever you play anything (unless you set it not to). If you want to set up your events only once, you can use transitions and set up the events on the transition (which is the approach I'd recommend) rather than adding them to the state after you play it.

> events for individual animations in the Mixer

`mixer.States[x].Events...`

Note that all child states in a mixer are always playing while the mixer is playing so they will trigger their events even if they currently have no `Weight`. If you don't want that you can check `AnimancerEvent.CurrentState.Weight` during the event.

> I don't want the animations to loop, but I do want to be able to recall the Mixer animation for the next attack animation in the chain

The [Playing and Fading](https://kybernetik.com.au/animancer/docs/examples/basics/playing-and-fading/) example explains the issue you're seeing when you reset the time.

Unfortunately, the `FadeMode.FromStart` introduced in the [Good CrossFade from Start](https://kybernetik.com.au/animancer/docs/examples/basics/playing-and-fading/#good-crossfade-from-start) section only works for `ClipState`s because it works by silently cloning the state and doing that with other state types would make controlling them much more complicated (you would then have multiple mixers and need to control all their parameters).

Are you actually using the mixer to blend between its animations or are you just picking one every time you attack? Because if you're just picking one then there's no need for a mixer at all, they could just be an array of `ClipTransition`s which you pick from. Then you can just enable their `Start Time` toggle in the Inspector and they would automatically use `FadeMode.FromStart` when you play them.

**Comment by KybernetikGames** [comment]
Copying the events from an `AnimationClip` was easy enough. If you have Animancer Pro, you can just add this method to the `AnimancerEvent.Sequence` class:

```
            /// <summary>[Pro-Only] Copies the <see cref="AnimationClip.events"/> into this <see cref="Sequence"/>.</summary>
            /// <remarks>
            /// The <see cref="callback"/> of the new events will be empty and can be set by
            /// <see cref="SetCallback(string, Action)"/>.
            /// <para></para>
            /// If you are going to play the `animation`, consider disabling <see cref="Animator.fireEvents"/> so that
            /// the events copied by this method are not triggered as <see cref="AnimationEvent"/>s. Otherwise they
            /// would still trigger in addition to the <see cref="AnimancerEvent"/>s copied here.
            /// </remarks>
            public void AddAllEvents(AnimationClip animation)
            {
                if (animation == null)
                    return;

                var length = animation.length;

                var animationEvents = animation.events;
                Capacity += animationEvents.Length;

                var index = -1;
                for (int i = 0; i < animationEvents.Length; i++)
                {
                    var animationEvent = animationEvents[i];
                    index = Add(index + 1, new AnimancerEvent(animationEvent.time / length, DummyCallback));
                    SetName(index, animationEvent.functionName);
                }
            }
```

If you only have Animancer Lite, it could easily be changed to an extension method.

**Comment by levidavidmurray** [comment]
Thank you for the detailed reply! And apologies for the delay, I was headed out for a week-long vacation as I posted this... 😅 

`ClipTransition` is exactly what I was looking for. I must have overlooked it when reading through the documentation.
