### ISSUE TITLE
Black screen in transition preview

### ISSUE THREAD

**Issue by ldkuba** [KybernetikGames/animancer#199]
Hi,

I've been using animancer for about half a year now and never had any problems. Today, when i tried previewing a transition in the preview window, the preview scene was black for any transition/model.

Photo of preview window:
![Capture](https://user-images.githubusercontent.com/7431324/160246327-fd19fcb4-6948-48d3-9d6e-4e81e708b6f8.PNG)

I'm using Animancer Lite: v6.1
Unity: 2020.3.3f1
and the Universal Rendering Pipeline

I'm not sure how to debug this on my own so i wonder if this looks like a familiar issue or a newbie mistake. I have a suspision that something is off with the lighting in the preview scene.

**Comment by ldkuba** [comment]
I also noticed that the Camera and Light components in `Settings` -> `Preview Scene Hierarchy` in the preview window inspector are disabled. I can manually enable the light components but i can't enable the Camera.

**Comment by KybernetikGames** [comment]
URP has caused issues with previews in the past, though I haven't seen a completely black screen before.

Do you get the same thing if you create a new project with just Animancer and URP? I just tried it and it worked fine.

Check if you can preview the Spider Bot in the Directional Blending example. It's possible there's something about your model that it doesn't like (though even if the camera ended up somewhere odd, the background colour should be dark grey rather than fully black).

It would also be worth trying the latest version of Animancer because the Transition Preview Window has been completely reworked and now renders like a normal scene view. Only try it in a new project at first though, because the [Animancer v7.0 Upgrade Guide](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-0/#upgrade-guide) has some important steps you need to follow if you upgrade an existing project.

The lights and camera being disabled isn't a problem, they get enabled by the preview window when it renders (otherwise they can interfere with some things in the regular scene if you have both the Scene and Preview windows visible at the same time.

**Comment by ldkuba** [comment]
Thanks for the help!

I managed to figure it out. My model had a small mesh which due to some import mistakes was far away from the rest of the model. The old preview window tried to display them all at the same time but it seems like the near and far planes are set to render a very narrow part of the scene so the model got clipped and the result was a black screen.

After upgrading to 7.2 everything works nicely. There is however, still one thing bothering me about the new preview window. There doesnt seem to be a light in the preview window scene. Is there any way or setting to controll lighting in the preview scene?

**Comment by KybernetikGames** [comment]
There's a toggle up the top of the Preview window to turn lighting on/off like in the regular Scene view, but I haven't implemented a way to actually add lights. It shouldn't be too hard to do though, so I'll take a look at it for the next version. Maybe the Settings panel could just have a field for you to specify an Environment prefab or even a whole scene asset.

**Comment by KybernetikGames** [comment]
[Animancer v7.3](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-3/) is now available and has a field in the Settings tab to assign a prefab which will be instantiated in the preview window so you can create your own lighting setup for it.
