### ISSUE TITLE
ClipTransition not ending

### ISSUE THREAD

**Issue by BenDol** [KybernetikGames/animancer#211]
Hello, I have tried for hours to resolve this issue and I'm not sure if it's a bug or if I am just doing something wrong here.

**Specs:**
- Windows
- Unity 2021.3.1f1
- Animancer 7.2

So, I have this ClipTransition defined:
![image](https://user-images.githubusercontent.com/1935706/172984986-c27573c4-d6bb-48a9-9182-3f85bad21306.png)

I am calling `Animancer.Play(transition)` like so:
![image](https://user-images.githubusercontent.com/1935706/172985079-9026b5f6-39c4-456f-a74f-9c44c622f8df.png)

When I observe the animation it never ends for some reason:
![neverendanim](https://user-images.githubusercontent.com/1935706/172985225-fbc21fa6-08cd-4976-b0f4-0f5b12c4bcce.gif)

Any ideas what might be going on here? Every other ClipTransition that I have defined doesn't have this issue.

Thanks!

**Comment by BenDol** [comment]
Do I need to manually set the animation state back to idle in these cases? I thought it should end and go back to the base animation. I cold be wrong though.

**Comment by KybernetikGames** [comment]
Animancer doesn't make any decisions on its own so you need to tell it when you want it to play something. There's no such thing as a "base animation".

The easiest way to do that is usually [End Events](https://kybernetik.com.au/animancer/docs/manual/events/end/).

Also, if you tick the `Start Time` toggle in the Inspector, you don't need to set the `Time` and `NormalizedTime` in code (and if you do want to do it in code there's no point in using both properties because they both control the same thing).

**Comment by BenDol** [comment]
Ah I see okay, I misunderstood this then. Thanks a lot for clarifying!
