### ISSUE TITLE
Unity AnimationEvent registered 0 frame will play end of Play() again

### ISSUE THREAD

**Issue by quxn6** [KybernetikGames/animancer#216]
# Environment

- Animancer Version Number :  7.3
- Animancer Pro or Lite:  PRO
- Unity Version: 2020.3.34f1
- Platform: windows 10

# Description
Unity AnimationEvent registered 0 frame will be called on end of [Animation Clip] again

# Reproduction
![image](https://user-images.githubusercontent.com/3910428/182575280-4b998921-5af6-4b89-93d6-d1519e991d02.png)

1. Register Unity Animation Event on animationClip (FBX)
2. Play that animationClip using Play([scriptname], 0.1f, NormalizedSpeed);
3. Enter the play mode and watch it.

**Comment by KybernetikGames** [comment]
I'm not seeing any issue by just following those reproduction steps, but it sounds very similar to [the other Animation Events bugs I'm aware of](https://kybernetik.com.au/animancer/docs/bugs/events).

So if you want to send me a minimal reproduction project I'll be happy to report it to Unity as a bug, but unfortunately there's nothing Animancer can do about it since it doesn't have any contact with the inbuilt Animation Events at all.

Instead, I'd recommend using [Animancer Events](https://kybernetik.com.au/animancer/docs/manual/events/animancer/) since I'm not currently aware of any bugs in that system (and if any are found, I can likely fix them).
