### ISSUE TITLE
Option to change behaviour of autoclearing Events from creating states in code?

### ISSUE THREAD

**Issue by thelebaron** [KybernetikGames/animancer#22]
I would personally like the option not to autoclear events from states when playing them. Maybe I'm not fully grasping the potential of how its currently structured, but I would find it pretty useful if when creating the state initially there was some bool to disable auto clear of events when that state played back.

**Comment by KybernetikGames** [comment]
The [Auto Clear](https://kybernetik.com.au/animancer/v4-0/docs/manual/events/animancer/#auto-clear) section explains why it works like that.

- Events in a state are cleared because any other scripts could be using the same animation and therefore the same state with their own events, so letting them interfere with each other's events is a great source of bugs.
- Events in a transition are not cleared, so they just assign their own event sequence to whatever state they play every time it is played.
- You can also make your own `AnimancerEvent.Sequence` and assign that to the state. It will be removed from the state as usual, but not cleared so you can always just assign it again next time.

Adding a simple `state.Events.AutoClear` bool is not out of the question, it just didn't seem necessary given the above options. I'll consider it over the next few days as I finish updating the 3D Game Kit example documentation before I release the final v4.0 Beta. Do you have a specific example you think this feature would be good for?

**Comment by thelebaron** [comment]
For the majority I tend to call the animations only from the characters that contain them, so in my own use its not an issue to always keep the event stored.  My case is an fps, so enemies are generally pretty predictable, and repeat their actions pretty often. I also prefer to hard code a lot of things, being a one man operation. 
I personally haven't made a whole lot of use of event pattern in my own experience in coding but having them auto clear just seems to run counter to how I personally expect to use them(and I can envision scenarios and uses for having this be the default behaviour, I would just appreciate an override of sorts).

**Comment by KybernetikGames** [comment]
It's not only for sharing between characters, it's also for using the same animation multiple times in the same character.

For example, imagine you have a `Gun` script with a `ClipState.Transition` for its *Reload* animation with an event at some point to call `Gun.ReloadUpdateAmmo` to actually reset the ammo. You have two guns that happen to use the same `AnimationClip` for reloading. After one of them is played and creates its state, both will use the same `AnimancerState` to play that animation, simply assigning their own events to it each time they are played. You don't want reloading the second gun to call `Gun.ReloadUpdateAmmo` on the first gun just because it had a leftover event from the last time it was played. And if another script tries to play that `AnimationClip` directly (without a transition), it won't want the leftover events from whatever used it before either. So without auto-clear you would be manually clearing the events every time you play anything, which is really annoying.

That raises a logistical issue with disabling auto-clear. If you disable it you would probably assume that the events you register will never get cleared. Except that if you then play a different transition, it will still want to use its own events so what should it do?

- Add its events to the existing ones? That would modify the previously assigned `AnimancerEvent.Sequence` so that it would have both sets of events whenever it is used again in the future.
- Create a new `AnimancerEvent.Sequence` to combine both sets of events? That would create a bunch of garbage every time.
- Replace the existing events? That achieves the same thing as auto-clear which the script that registered those events will not be expecting because it disabled auto-clear so it will not know that it needs to re-assign its events.
- Allow each individual event to indicate whether it should be auto-cleared? This would avoid the above issues, but would add a bunch of implementation complexity and cost a lot more performance than any of the other options.

**Comment by thelebaron** [comment]
I'm trying to parse this scenario but its a little unclear to me: Would it not make more sense to split these two guns into two separate `AnimancerComponent` setups rather than trying to share them into having some similar reuse but also some different states? 

Lets say in this particular case
`// MeleeAttack.cs:
[SerializeField] private AnimancerComponent _Animancer;
[SerializeField] private AnimationClip _Animation;
private AnimancerState _State;

public void Start()
{
    _State = _Animancer.States.GetOrCreate(_Animation);
    _State.autoclearEvents = false;//just made up 

    // Call OnHitStart to activate the hit box when the animation passes 40% of its length.
    _State.Events.Add(0.4f, OnHitStart);

    // Call OnHitEnd to deactivate the hit box when the animation passes 60% of its length.
    _State.Events.Add(0.6f, OnHitEnd);

    // Return to Idle when the animation finishes.
    _State.Events.OnEnd = EnterIdleState;
}
public void Attack()
{
    _Animancer.Play(_State).Time = 0;
}
`
Assuming this is pretty much how states are structured with only the enclosing class assigning events to states, there shouldnt be any worries of logistical mixup, it's self contained only to the MeleeAttack script.
Maybe its just a mindset for the workflow that I need to get over? Anyway will give this more thought.

**Comment by KybernetikGames** [comment]
But that's not entirely self-contained because if any other script references the same `AnimationClip` assigned to `_Animation`, when that script plays it the same state will get used so its events would still call those methods in this `MeleeAttack` script. That might not seem very likely for a *Melee Attack*, but what about something like *Cast Spell* where you could have several different actions with the same animation? You can't just have each action assuming its events will stay there unless you use `States.Create` (instead of `GetOrCreate`) to ensure that each one has its own separate state which would waste a bunch of performance for each additional one.

But if you just use a transition you save a few lines of code and don't run into that problem:

```
[SerializeField] private AnimancerComponent _Animancer;
[SerializeField] private ClipState.Transition _Animation;

public void Start()
{
    _Animation.Events.Sequence.Add(0.4f, OnHitStart);
    _Animation.Events.Sequence.Add(0.6f, OnHitEnd);
    _Animation.Events.Sequence.OnEnd = EnterIdleState;
    _Animation.StartTime = 0;
}
public void Attack()
{
    _Animancer.Play(_Animation);
}
```

Playing the transition assigns its events to the state and playing the same animation somewhere else will not have to worry about irrelevant events.

That also means you can use the hybrid approach I described in the new [Golf Events](https://kybernetik.com.au/animancer/v4-0/docs/examples/events/golf/) example where you set up the event times in the Inspector using the Transition Preview Window so properly adjust them according to the animation, then set the actual callbacks in code on startup.

**Comment by thelebaron** [comment]
Are you talking about referencing `_Animation` like 
```//Character.cs
var meleeAtk = GetComponent<MeleeAttack>();
_AnotherAnimancerComponent.Play(_Animation);
```
Or do you mean referencing the actual physical AnimationClip asset located within the source `*.fbx` or equivalent file?
If its the former `_Animation` being private shouldn't be accessible and that shouldn't be a problem. If its the latter well then I am totally misunderstanding how this functions in relation to `transitions`.

Comparing the performance of both 'Transition's and caching actions for use with 'AnimancerState's shows that using transitions results in some gc allocations. It's not too frequent but ideally id like to avoid triggering gc if I can help it.

**Comment by KybernetikGames** [comment]
> Or do you mean referencing the actual physical AnimationClip asset located within the source *.fbx or equivalent file?

Yeah, that.

Like if you were to use two of your `MeleeAttack` components on the same character (one regular attack and a skill that references the same `AnimationClip` asset then one would create a state and the other would be given the same state by `States.GetOrCreate` so they would both add their events to the same state, giving you two each of `OnHitStart` and `OnHitEnd` (but still only one `OnEnd` event).

But with my `MeleeAttack` component, each transition has its own sequence of events so they remain separate. Then whenever you play one of those transitions it uses the same state but assigns its own events so you don't need to care whether or not something else might have used that same state for something else.

> Comparing the performance of both 'Transition's and caching actions for use with 'AnimancerState's shows that using transitions results in some gc allocations. It's not too frequent but ideally id like to avoid triggering gc if I can help it.

I think you're misunderstanding how the GC works.

GC allocations are what you see when it allocates memory that will *at some point* need to get garbage collected.

The real problem is actual Garbage Collection because it needs to go through all allocated memory and figure out which objects are no longer being referenced from anywhere, which is expensive.

So the `Start` method in your `MeleeAttack` example would show some GC Alloc when `States.GetOrCreate` makes a new `ClipState`, and when accessing `_State.Events` creates a new `AnimancerEvent.Sequence`, and when the first call to `Add` initialises the sequence from empty to an actual array that can hold things, and also when creating the delegates for each of the 3 methods you are assigning. But none of that will actually become garbage until that component is destroyed and nothing is left referencing it.

The first time you play a transition it will show GC Alloc for similar reasons, but after that it should not cause any more allocations or create any actual garbage (and if it does let me know because that would be something I want to fix).

I wrote a bit about [Memory Management](https://kybernetik.com.au/animancer/v4-0/docs/introduction/cs/other/#memory-management) in the documentation.

**Comment by thelebaron** [comment]
Re - Referencing the physical asset file - ok, I guess does sound like a much bigger deal than what I originally envisioned it being. That said I still am almost positive I wouldn't be using it in the case that you outline(at least in this project), there is pretty much a 1:1 ratio for clips to unique methods to each character, which itself remains self contained as far as animations go. Its definitely a simple setup, perhaps insultingly so, but never the less I felt like what currently stands is almost too protective. In my perfect world I would like to keep all the setup(subscribing events etc to states) on one section, so when I change the state I don't have to worry about retelling it to have x,y and z events at these various points.

As for GC, yes that was poor phrasing on my part. I want to avoid any allocations except for intialising in start or awake. There do seem to be intermittent gc allocations when using transitions but none when caching actions for states. I did notice that the most recent release from this morning seems to actually make things worse, b6 was every x frames and in this release its every frame(both transitions and cached action states)

**Comment by KybernetikGames** [comment]
I'm pretty sure I haven't intentionally touched anything recently that should cause allocations (and certainly not every frame) so that's definitely a bug.

Can you turn on Deep Profiling and figure out where the allocations are actually coming from? And better yet, if you can track it down to something that happens in any of the examples that would make it much easier for me to find.

**Comment by thelebaron** [comment]
first image is from the latest update in the events golf swing demo https://i.imgur.com/ExE7wss.png

second is from b6, using transitions(the intermittent allocation, model was duplicated a few hundred times so that represents many animancer components) https://i.imgur.com/L3AiyBv.png

**Comment by KybernetikGames** [comment]
Looks like I found two problems for the price of one. :)

Firstly, I wasn't thinking when writing the assertions in the Animancer Event system. Calls to `Debug.Assert(condition, thing + " blah blah blah")` will get compiled out when `UNITY_ASSERTIONS` is not defined (i.e. in runtime non-development builds so the allocations you are seeing would not happen in a proper build), but when that symbol is defined it needs to evaluate all the parameters fully before calling the method, meaning that it still has to build the message string (which allocated memory) even if the condition is true so it doesn't actually log that message. So I just had to change them to:

```
#if UNITY_ASSERTIONS
if (!condition)
    Debug.LogError(thing + " blah blah blah");
#endif
```

And secondly ... somehow I got the packages mixed up and uploaded the Lite version instead of Pro.

So anyway, you can grab Release Candidate 2 which should fix the problem.

Also, it will still allocate some when returning event sequences to the `ObjectPool` if it needs to expand the internal list, but you can set the static `AnimancerState.EventPoolCapacity` to some value larger than the number of characters you are likely to have on startup if you want to avoid that.

**Comment by thelebaron** [comment]
Thanks for the update, seems to clear up the allocations in both instances.
