### ISSUE TITLE
Addititive sprite animations

### ISSUE THREAD

**Issue by starfckr** [KybernetikGames/animancer#223]
Limitations in how the spriterenderer works makes it impossible to additively blend animations using Animancer.
Ideally it would be great if Animancer could natively support blending sprites over multiple different layers, to be able to:

- Create your own custom transitions where old animation fades out, whilst the new animation fades in
- Play the same animation on two layers (timeshifted to achieve a blurred effect)
- Play two different animations at the same time on different layers (e.g. complex animations like swimming, etc, where you want too blend between layers dynamically at run-time)

**Comment by KybernetikGames** [comment]
Can you explain what you're doing with events that prevents having multiple `AnimancerComponent`s from being a viable option?

**Comment by KybernetikGames** [comment]
I've got the proof of concept working, but I'm not sure how useful it will actually be. It creates a blur-like effect during transitions as you'd expect, but you can also see the character's overall colour change as well which looks silly (it's particularly obvious with the mage on the left):

![SpriteBlending](https://user-images.githubusercontent.com/43698611/212469625-ad9890a7-67c9-4529-bc6d-e85766c7584a.gif)

It's simply due to the way alpha blending works. Imagine you have two active sprites being blended:

- Background colour (0,0,1)
- Sprite 1 colour (1,0,0) with alpha 0.5
- Sprite 2 colour (0,1,0) with alpha 0.5

The resulting colour would be:

- Start with the background (0, 0, 1)
- Blend 50% from there towards Sprite 1 = (0.5, 0, 0.5)
- Blend 50% from there towards Sprite 2 = (0.25, 0.5, 0.25)

Neither of the sprites contain any blue, but the final colour is has 0.25 blue, as if the character was 25% transparent, meaning you can see the background through the character. So I can't see any way for it to actually look good for regular transitions.

> Play the same animation on two layers (timeshifted to achieve a blurred effect)

That would probably work as long as the base layer is always at 1 weight, but could be implemented way easier without needing any contact with the animation system. Just have a second `SpriteRenderer` with reduced alpha and whenever the sprite on the main renderer changes, give the previous sprite to the second one. That would be way more efficient and you wouldn't need to mess around with playing all your animations multiple times or lining up their offsets based on the animation frame rate or anything like that.

> Play two different animations at the same time on different layers (e.g. complex animations like swimming, etc, where you want too blend between layers dynamically at run-time)

That could avoid the transparency issue as long as you always have the base layer at 1 weight, but I'm struggling to imagine what you might be trying to blend with a swimming animation that could actually look good. And that could easily be achieved by just having one Animator+AnimancerComponent+SpriteRenderer per layer.

So as it stands, I can't see this becoming an actual useful feature and don't plan on doing a proper implementation to include in Animancer.
