### ISSUE TITLE
When adding event to Transition.Clip, preview settings is collapsed

### ISSUE THREAD

**Issue by thelebaron** [KybernetikGames/animancer#23]
![image](https://i.imgur.com/wazjwBq.png)

Bug/Unwanted behaviour - When using the preview, scrubbing the clip(blue circled part) is the easiest way to get to a point in an animation. If an event is added (red), the particular clip is collapsed and time reset back to zero(blue), would be nice if this didn't happen.

Idea: Would be handy would be if you could drag an event after adding one rather than needing to delete and re-add it.
Second idea: If the above is possible, it would be extra handy to scrub the animation to the time that the event is being dragged at.

**Comment by KybernetikGames** [comment]
> When using the preview, scrubbing the clip(blue circled part) is the easiest way to get to a point in an animation.

You can scrub the time using the event timeline which properly accounts for the Previous and Next animations as well. Otherwise changing the state time directly (blue circle) would not change the time or weight of the other animations since that's part of the regular AnimancerComponent Inspector that has nothing to do with transitions.

> If an event is added (red), the particular clip is collapsed and time reset back to zero(blue), would be nice if this didn't happen.

If you change the transition's clip, it needs to destroy and recreate the state with the new clip which also destroys its drawer so it forgets it was expanded. The easiest way I found to implement that was to just do it whenever pretty much anything changes. Both of those aspects are undesirable so I intend to look at improving them for the next version.

> Would be handy would be if you could drag an event after adding one rather than needing to delete and re-add it.

You can drag the event time field like a regular float field. You can't drag the event icons because dragging the timeline already sets the time and I didn't want it to let you accidentally modify an event time when you are only trying to preview a different part of the animation.

> If the above is possible, it would be extra handy to scrub the animation to the time that the event is being dragged at.

Changing the event time already does set the preview to that time.

**Comment by thelebaron** [comment]
I know you can scrub the time on the float field but its just imprecise compared to dragging the actual slider representation. 

I figured it it was something to do with destroying and recreating the state, but thought it would be worth adding as a request.

What about holding control or shift or some key in order to prevent accidental selection clicks moving the event icon? Or using arrow keys to nudge it left or right? 

Lastly would it be possible to give events names? Just for purposes of clarifying things in the inspector, rather than going by Event0/1/2/3 etc

**Comment by KybernetikGames** [comment]
> I know you can scrub the time on the float field but its just imprecise compared to dragging the actual slider representation.

It should be more precise because it has a larger area than the slider. But I could add a Time field between the Next Animation and Overall Speed so you can properly type the number.

> What about holding control or shift or some key in order to prevent accidental selection clicks moving the event icon? Or using arrow keys to nudge it left or right?

Those sound like good ideas.

> Lastly would it be possible to give events names? Just for purposes of clarifying things in the inspector, rather than going by Event0/1/2/3 etc

I've avoided making editor-only serialized fields because they cause errors in runtime builds if they are inside a precompiled DLL rather than a script Unity compiles. But the Lite version already has a lot of inefficiency so I guess I could just leave them in at runtime for the Lite version.

That would also allow you to do something like `transition.Events.AssertName(0, "Hit")` to ensure that it actually has the events you expect rather than only asserting that the count is correct.

**Comment by thelebaron** [comment]
Ok silly me, what I had circled red I originally didn't actually realize was actually draggable, so a good chunk of this complaint is not necessary. Still, I would like nudging of event icons.

**Comment by KybernetikGames** [comment]
The issue with the animation details being collapsed all the time is now fixed in [Animancer v4.1](https://kybernetik.com.au/animancer/docs/changes/animancer-v4-1).

Being able to nudge event times is still on my ToDo list.

**Comment by KybernetikGames** [comment]
I just released [Animancer v4.2](https://kybernetik.com.au/animancer/docs/changes/animancer-v4-2) which lets you nudge event times with the arrow keys (hold Shift to go further) and also round one decimal place off the event time by pressing space.
