### ISSUE TITLE
Transitioning mixer parameter causes events to fire multiple times in single frame

### ISSUE THREAD

**Issue by tylorr** [KybernetikGames/animancer#231]
# Environment

- Animancer Version Number: 7.2
- Animancer Pro or Lite: Pro
- Unity Version: 2020.3.35f1 and 2021.3.11f1
- Platform: Windows and Mac

# Description
I have a linear mixer transition asset with two animation clips in it. One marked as sync and the other not to sync. I have an animation event registered to the mixer asset. At runtime while transitioning the mixer parameter between the two clips it seems that the event gets fired multiple times within the same frame. 

Inside `EventDispatcher.CheckGeneralEvents` the difference between `_PreviousTime` and `currentTime` is large which I believe it makes the system think that multiple loops have been missed so it plays the event for each one.

This issue does not reproduce if both the animation clips have the `sync` field set to true. In any other combination of sync values the problem does occur. 

If this is intended behavior then I need some help trying to achieve what I'm trying to do

# Reproduction

Steps to reproduce the bug:

1. Create a linear mixer animation asset
2. Attach a single event to the mixer that prints the unity frame count
3. Add two animation clips that loop, each with different parameter values (easiest to test with animations around 1sec in length)
4. Set only one animation clip to sync and the other to not sync
5. Play the game and transition the mixer parameter such that the animations blend between each other
6. See that multiple logs from the event have triggered for the same frame

**Comment by KybernetikGames** [comment]
The issue comes from `MixerState.Length` and `RawTime`. If none of the active animations are synced, they will use the weighted average of all active animations, but if any of the active animations are synced then they will use the weighted average of those synced animations only.

My theory was that if you have Idle/Walk/Run and you set the time, you most likely care about the Walk/Run cycle even if the parameter is so low that Walk is barely active. So yeah it's by design.

I'm not necessarily opposed to changing it to always be a weighted average of everything. I can't remember why I changed it to be like this so I'd have to figure out when I made the change. That would give the same result as nothing being synced in the current system and nothing is really synced anyway if you only have one synced so try disabling sync on all the animations and let me know if the result is what you were hoping for.

**Comment by tylorr** [comment]
I'm seeing the same behavior with syncing disabled for all clips. I haven't tried this with our idle/walk/run mixer yet but I'm worried I'm going to get spammed with events when switching from idle to walk. Is there another way to setup events that avoids this issue?

**Comment by KybernetikGames** [comment]
If you use [Transition Assets](https://kybernetik.com.au/animancer/docs/manual/transitions/assets/) for each of the animations in the mixer, you can give them each their own events. But that would mean separate events for Walk and Run, which would both be getting triggered while you're blending between them.

But with the events on the mixer, all you could really do is check if the mixer is idle every frame so that when an event occurs you can ignore it if the mixer was idle last frame.

**Comment by KybernetikGames** [comment]
Another option would be to not use the mixer while fully idle. Keep idle in the mixer if you want to control low speed movement, but if you would set the parameter to 0 just play the idle animation as a regular animation clip outside the mixer, then play the mixer when you start moving again.
