### ISSUE TITLE
Is there any plans to make some graph of animations and transitions like Unity Animator Controller?

### ISSUE THREAD

**Issue by Dukobpa3** [KybernetikGames/animancer#238]
# Use Case

Make complicated graphs in more comfortabe visual way

# Solution

xNode – https://github.com/Siccity/xNode

# Alternatives

Doing it with code like now is also great(in case of runtime changes etc...), but if we can keep both options – Animancer will achieve next level :)

**Comment by KybernetikGames** [comment]
I have plans to implement [Transition Sets](https://github.com/KybernetikGames/animancer/issues/80) which could somewhat resemble Animator Controllers in the sense that they could visualise the relationships between animations, but not in regards to actual state machine logic. The current idea is for a data management system where you can say *"I'm in State A, give me the appropriate Transition to get to State B"*, but **not** for a logical control system where you can say *"I set the 'Jump' parameter to true"* and expect the system decide what to do with that. The former is a reasonable extension of an animation system, but the latter would essentially require a visual scripting system so I'd recommend using a dedicated plugin to do that properly rather than trying to squeeze it in with animations. I'm also just not a big fan of visual scripting in general. I have some ideas for approaching the problems mentioned in that thread but nothing concrete yet so any suggestions would be most welcome.

If you were thinking of a full logical control system, I'd be interested in hearing more details about how scripts would interact with this system and what you would want it to be able to do which can't currently be done with the existing options for using [Animator Controllers](https://kybernetik.com.au/animancer/docs/manual/animator-controllers/) alongside Animancer.
