### ISSUE TITLE
3D Game Tutorial example IsGrounded on moving platforms

### ISSUE THREAD

**Issue by Craigjw** [KybernetikGames/animancer#24]
In the example for the 3D Game Kit tutorial, the CharacterController incorrectly reports IsGrounded when the player is on a moving platform, causing the player to be in an airborne state rather than in a grounded state.

**Comment by KybernetikGames** [comment]
I just had a quick look at it and can confirm inconsistent behaviour on moving platforms on the Animancer character. It doesn't happen on the Mecanim character but I can't figure out why because as near as I can tell I should be applying the exact same movements to the character. I'll have to look into it more for the next version.

**Comment by KybernetikGames** [comment]
This is now fixed in [Animancer v4.1](https://kybernetik.com.au/animancer/docs/changes/animancer-v4-1).
