### ISSUE TITLE
Nuget Package Support

### ISSUE THREAD

**Issue by stonstad** [KybernetikGames/animancer#240]
Hi Animancer!

I'm a paid user and I greatly enjoy your product.  Thank you for creating it.  My question: if it does not already exist, would you consider distribution as a nuget package?  The reason I ask is that I'd like to decrease the number of csproj files in my solution due to asmdef definitions -- for faster compilation and simplicity.  Right now, I have two Animancer projects in my solution due -- which I never edit or touch.  A nuget package would resolve this, I believe.  

Thanks,
Shaun

**Comment by KybernetikGames** [comment]
I'd consider it if there was an easy way to handle purchases. From my understanding, paid Nuget packages need the author to handle all the payment stuff themselves and give users a code which unlocks the full functionality of the package, but even if I could figure out the actual payments, unlocking functionality simply wouldn't work when Animancer Pro includes its source code.

One of the pain purposes of Assembly Definitions is to improve compilation speed though. If you modify one of your scripts, it won't need to recompile Animancer because Animancer' asmdef doesn't reference the assembly your script is in.

Another option would be for you to compile the source code into a DLL, but that would take a bunch of effort and I wouldn't expect a notable compilation speed increase.

**Comment by stonstad** [comment]
I appreciate the consideration.  Thank you!
