### ISSUE TITLE
Bicubic transition interpolation

### ISSUE THREAD

**Issue by RomanZhu** [KybernetikGames/animancer#243]
I want to mimic https://youtu.be/LNidsMesxSE?t=422
He has only a few keyframes, and with clever blending able to get compelling results

And if you saw it already, do you have a general idea of the setup for such a system?

My idea is: I will need to play idle/walk/run clips in sync, I will adjust their weights based on my current speed
However, I can't see how I can do bicubic interpolation during transitions

**Comment by KybernetikGames** [comment]
For regular states, the [Custom Fade](https://kybernetik.com.au/animancer/docs/manual/blending/fading/custom/) system lets you apply a curve to the transition.

[Mixers](https://kybernetik.com.au/animancer/docs/manual/blending/mixers/) are the easiest way to play multiple animations in sync. As explained on the [Mixer Synchronization](https://kybernetik.com.au/animancer/docs/manual/blending/mixers/synchronization/) page, it's usually best to only synchronize related animations (i.e. walk and run) but turn it off for unrelated ones like idle since its time doesn't correspond to the same walk cycle as walk and run.

The Custom Fade system doesn't work for children of Mixers though because their weights are usually calculated by the Mixer when you set its Parameter. But the [Mixer Smoothing](https://kybernetik.com.au/animancer/docs/manual/blending/mixers/smoothing) page explains how you can smoothly modify a Mixer's Parameter over time so it should be pretty easy to adapt one of those approaches to use bicubic interpolation instead of linear.
