### ISSUE TITLE
Issue with 2022.2.1f1, issue likely with SoloAnimation

### ISSUE THREAD

**Issue by Sea-Fog** [KybernetikGames/animancer#245]
# Environment

- Animancer Version Number: 7.3
- Animancer Pro or Lite: Pro
- Unity Version: 2022.2.1f1
- Platform: Windows

# Description

Whenever a clip is playing and destroyed, the object, instead of returning to its original local position/rotation, will go to its parent's local position/rotation. No issue in 2022.1.23f1 and prior. The issue is with 2022.1f1 (and likely forward).
![Before Start](https://user-images.githubusercontent.com/9471573/212484618-8420c343-bc9d-400a-9114-245de7128389.png)
I attach an AnimancerComponent and play an animation. (When good) I stop it and destroy it; it returns to its original position/rotation. 
![After Stopping Good](https://user-images.githubusercontent.com/9471573/212484696-0eca3b0c-2c1c-41b5-bb56-28d4e4a6ef68.png)

When I upgrade to 2022.2.1f1, I get this warning:
![Update Consent Warning](https://user-images.githubusercontent.com/9471573/212484723-b66b8147-fd1a-4699-bb94-2696ffa1b521.png)
It doesn't matter if I accept the change or not; this is how the object will finish after stopping and destroying the AnimancerComponent.
![After Stopping Bad 2022_2_1f1](https://user-images.githubusercontent.com/9471573/212484829-1754a61e-7cb1-4e21-809d-2fecb0ade730.png)

If I go back to an earlier editor version and reimport the SoloAnimation script, it works again. Here is the warning before I reimport:
![DebugLog Going Back to 2022_1_23f1](https://user-images.githubusercontent.com/9471573/212485173-e3f3ec9c-349e-43a5-925d-1699a6d9910d.png)

Here is the code that you can use to duplicate the issue with a simple Scene :
"
using Animancer;
using Animancer.Examples.StateMachines;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using static UnityEditor.Progress;

public class Test : MonoBehaviour
{
  public AnimationClip clip;
  private Transform parentTransform;
  private Vector3 lPosition;
  private Quaternion lRotation;

  private void Start()
  {

    lPosition = transform.localPosition;
    lRotation = transform.localRotation;

    parentTransform = this.transform.parent;
    GameObject tempGameObject = new GameObject(this.name + " temp Parent");
    tempGameObject.transform.position = this.transform.position;
    tempGameObject.transform.rotation = this.transform.rotation;
    tempGameObject.transform.parent = parentTransform;
    this.transform.parent = tempGameObject.transform;

    AnimancerComponent animancer = transform.AddComponent<AnimancerComponent>();  
    animancer.Animator = transform.AddComponent<Animator>();

    var state = animancer.Play(clip);

  }

  private void Update()
  {
    if (Input.GetKeyDown(KeyCode.Space))
    {
      GameObject tempGameObject = transform.parent.gameObject;

      this.transform.parent = tempGameObject.transform.parent;

      AnimancerComponent animancer = GetComponent<AnimancerComponent>();
      animancer.Stop();

      transform.localPosition = lPosition;
      transform.localRotation = lRotation;

      Destroy(this.GetComponent<AnimancerComponent>());
      Destroy(this.GetComponent<Animator>());
      Destroy(tempGameObject);
    }

  }
}
"

**Comment by KybernetikGames** [comment]
The `SoloAnimation` thing won't have anything to do with your issue. It's just because `Animator` used to have a `keepAnimatorControllerStateOnDisable` property which is now deprecated because they added `keepAnimatorStateOnDisable`. The documentation is the same for both so I assume they just wanted to rename it. I've fixed that and a few other minor issues with Unity 2022.2 in the upcoming [Animancer v7.4](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-4).

I haven't been able to replicate the behaviour you described though. I tested it in the Root Motion example and found that Unity 2022.2 resets the character to their T pose when destroyed (unless I set `Animator.keepAnimatorStateOnDisable = true` or don't destroy the `Animator`) but the position of the character in the scene seems to be consistent between 2022.2 and older versions. I only have Unity 2022.2.2f1 installed though so there's a chance that updating might solve your issue, but otherwise can you explain your setup in a bit more detail?

**Comment by Sea-Fog** [comment]
Thank you for the quick response. The Animator is the issue. If I destroy it in the same frame, that is where the issue is coming in, a delay makes it work perfectly. Thank you for your help.
