### ISSUE TITLE
Enemies in 3D Game Kit Lite example are broken.

### ISSUE THREAD

**Issue by Woofur1n3** [KybernetikGames/animancer#249]
Dear developer,

I noticed that everything is working fine in the 3D Game Kit example except the enemies are not moving and attacking when using Ellen with Animancer. Everything is working fine if I switch to mechanim version. 

Can you advise on this?

I would like to use 3D Game Kit completely with animancer pro.

Thanks and regards.

**Comment by KybernetikGames** [comment]
Unfortunately, the 3D Game Kit wasn't designed to be at all modular. From what I can remember, the enemy scripts directly interact with the main `PlayerController` component that basically does everything for the Mecanim character. So you would need to go into those scripts, figure out what they're trying to do, and edit them to do something similar with the Animancer character. It might be simple to do, I just wasn't able to do it as part of my example because it would mean I'd need to include the edited script and everything it depends on in Animancer, which would take way more effort than it's worth for a single example.

**Comment by Woofur1n3** [comment]
Thanks a lot! I actually miss out this portion in the documentation.
