### ISSUE TITLE
Method Summary in document pages do not wrap or scroll horz. 

### ISSUE THREAD

**Issue by mikech2000** [KybernetikGames/animancer#290]
The method summary column on document html pages do not wrap and the table does not scroll horizontally. 
I noticed that this is not always the case, but is true of LinearMixerState and maybe others?

**Comment by KybernetikGames** [comment]
It's caused by long member references which aren't allowed to wrap like this:
![image](https://github.com/KybernetikGames/animancer/assets/43698611/05d963a3-def2-4416-8f3b-aefd553d7a3b)
Having any of those in the table increases the width of the whole column even if other cells could word wrap in a reasonable space. It does give the table a horizontal scroll bar, it's just right down the bottom. You can also click and drag to select text to make it scroll over or just zoom out.

A while ago I reported it as a bug to the developer of the documentation generator I use (Wyam) so he's aware of it, but he's currently working on a completely new system so the old one isn't getting any bug fixes. Unfortunately, I'm not confident I could figure out how to fix it in a reasonable amount of time.

**Comment by mikech2000** [comment]
That ok.
Thanks for the reply.
Mike
________________________________
