### ISSUE TITLE
ClipTransition lag and hanging Unity (possibly only when serialized inside an ODIN SerializedScriptableObject)

### ISSUE THREAD

**Issue by virtushda** [KybernetikGames/animancer#313]
# Environment

- Animancer Version Number: 7.4.2
- Animancer Pro or Lite: Pro
- Unity Version: 2022.3.4f1
- Platform: Windows

# Description

Serializing 'ClipTransition's in a list or dictionary inside ODIN's SerializableScriptableObject causes multiple problems.
Drawing the inspector for a clip transition is extremely laggy and slow, without changing any values.
More critically, adding or removing seems to trip some internal Unity undo state generation and Unity hangs forever.

**Comment by KybernetikGames** [comment]
Sorry for the slow response, I'm not sure why I didn't see this post.

Unfortunately, I don't have Odin so I can't replicate the issue. If you can send a minimal reproduction project to animancer@kybernetik.com.au I'd be happy to take a look at it. Otherwise, you could report this issue to the Odin devs and they should be able to replicate it with Animancer Lite.
