### ISSUE TITLE
TimeLine Play bug 

### ISSUE THREAD

**Issue by f123888** [KybernetikGames/animancer#319]
# Environment

- Animancer Version Number:  7.4.2
- Animancer Pro or Lite:  Pro
- Unity Version:  2022.3.1
- Platform: Windows10

# Description

The Timeline asset is working well when you first creat it in animancer preview. But if you preview it in timeline with Playable director. The animantion will be default Pose(T pose) in animancer Transition field. it still don't work after I cancel the bindings. The timeline version is 1.7.6

# Reproduction

Steps to reproduce the bug:

1. Just create a timeline with a humanoid animation. 
2. Preview with Playable director
3. preview in the animancer Transition field.
`[SerializeField]
private PlayableAssetTransition _Animation;`

**Comment by KybernetikGames** [comment]
Unfortunately, this looks like a Unity bug and I haven't been able to find any way to work around it so I've reported it to Unity.

I've seen a lot of bugs that happen because Timeline was never really designed to be used outside a PlayableDirector, but this one is honestly the strangest. I'm not even aware of any way to have the animation system intentionally put a humanoid character back into its T pose because the default humanoid pose is this hunched over position:
![image](https://github.com/KybernetikGames/animancer/assets/43698611/523d3aff-ef4f-4ab8-9867-82992a9c143f)
Beyond that, there also doesn't seem to be any way to fix it once it's broken other than entirely closing Unity.

**Comment by KybernetikGames** [comment]
[This issue is now up on Unity's Public Issue Tracker.](https://issuetracker.unity3d.com/issues/custom-playablegraph-stops-working-when-making-edits-in-the-timeline-window)

**Comment by f123888** [comment]
I have the same problem. I am trying to use Timeline as a skill editor integrated into Animancer, but when the animation involves Root Motion, the Root Motion output from Timeline is a mess. It seems that this approach is not feasible.  (ㄒoㄒ)
