### ISSUE TITLE
Animation Events stopped working

### ISSUE THREAD

**Issue by FrogsInSpace** [KybernetikGames/animancer#33]
# Environment

- Animancer Version Number:  4.3
- Animancer Pro or Lite:  Pro
- Unity Version: 2019.2.21f1
- Platform:  Windows Editor

# Description
Since the upgrade to 4.3 , Unity animation events are not triggered any longer for my sprite animations in the build nor in editor play mode or edit mode. I use them to trigger sounds at specific frames and also use a end of anim marker event on the last frame ... 
I load and play the animations via  Animancer Component
As soon as i revert back to Animancer V4.2, events begin to work again as usual

Sorry for not being able to provide more details, but currently my available time is very restricted :)

**Comment by KybernetikGames** [comment]
Animation Events seem to work fine for the Events examples and any of the other Humanoid examples I try it on, but not on Generic rigs (including Sprites). I have no idea why that might be (Animancer doesn't treat them any differently), but I'll keep looking into it.

**Comment by KybernetikGames** [comment]
I've found a workaround:

- Go to the constructor of `AnimancerLayer`.
- Comment out `: base(root)`
- Add in `Root = root;` and `CreatePlayable();` after setting the `Index`.

What I can't figure out is why it was working at all in the first place. `CreatePlayable` connects the playable to its parent, but `base(root)` calls it before setting the `Index` meaning it tells Unity to connect it at index -1 which obviously shouldn't work. Trying to connect to -2 gives an error. Trying to connect to 1 gives an error. But trying to connect to -1 seems to allocate a new port for it so Layer 0 leaves port 0 unconnected and creates and connects to port 1 instead, and that somehow allows it to function properly in every way ... except for triggering Animation Events.

Looks like it's time to report yet another bug in the Playables API.

**Comment by FrogsInSpace** [comment]
Hey thanks for that quick reaction ... will test the workaround ASAP and report back the outcome
Have to confess that i still did'nt touch playable API till now, but still i find it interesting to hear about your findings

**Comment by KybernetikGames** [comment]
I think this is actually an old bug.

Using -1 to tell it to create and connect to a new port isn't entirely unreasonable (it's probably intentional, just undocumented).

But I reported another bug ages ago where an `AnimationLayerMixerPlayable` will ignore the input weights if there is only one thing connected and play the animation but not trigger any events. So what's actually happening here is that Animancer allocates 1 input port, tells Layer 0 to connect to port -1 which allocates and connects to a second port, but then once its Index gets properly set to 0 it sets the weight of the first port which it isn't connected to. So it's controlling the weight of port 0 but actually connected to port 1 which stays at 0 weight, and since it is the only thing connected it still looks like it's playing properly without triggering its events.

I would not recommend trying to use playables directly if you can avoid it. It's not at all user friendly, has terrible documentation, and I've run into at least a dozen bugs like this which are almost all still there since it seems to be such a low priority. For example, in the documentation for the Simple Animation Component (made by Unity themselves) there's a section which explains that you can set it to [disconnect clips from the graph when they aren't playing](https://github.com/Unity-Technologies/SimpleAnimation/wiki#simpleanimation-doesnt-support-only-writing-the-values-of-the-current-clip-by-default) to prevent them from writing their values to the animated object every frame (so you can control those values freely in scripts). That's a really useful feature ... or at least it would be if not for the fact that the Playables API doesn't actually work like that (I haven't found any way to get it to stop writing a value every frame once it has started, even destroying old playables doesn't help).

**Comment by FrogsInSpace** [comment]
Just post to confirm that the fix above worked perfectly for me 
Thanks again for your swift response and for Animancer in general !

**Comment by KybernetikGames** [comment]
This is now fixed in [Animancer v4.4](https://kybernetik.com.au/animancer/docs/changes/animancer-v4-4).
