### ISSUE TITLE
Example for Network？

### ISSUE THREAD

**Issue by LaoBowen** [KybernetikGames/animancer#337]
Hi~ I'm trying to use Animacer in my multiplayer project.
Can we have some more documentation or examples on how to synchronize animation on network? Netcode for Gameobjects for example.
Thank you!

**Comment by KybernetikGames** [comment]
[My very limited understanding of networking is explained here.](https://kybernetik.com.au/animancer/docs/manual/fsm/overview#networking). These threads https://github.com/KybernetikGames/animancer/issues/203 and https://github.com/KybernetikGames/animancer/issues/210 might also be helpful.

The Transition Libraries feature I'm working on for [Animancer v8.0](https://github.com/KybernetikGames/animancer/issues/295) should help with networking by allowing a serializable identifier which can be used to look up the corresponding animation on the other side.

After that, the next major feature I'm planning is [Inertialization](https://www.gdcvault.com/play/1025165/Inertialization) which will also help with networking by replacing cross fading so there's only ever one active state per layer so the data you need to network is smaller and consistent.

With those features it should be possible to properly generalise a networking system for Animancer and make examples for it. I also have a bunch of other plugins and projects to work on so that certainly won't be happening any time soon.
