### ISSUE TITLE
How to change root of animation for preview?

### ISSUE THREAD

**Issue by wrymn** [KybernetikGames/animancer#339]
I have a following setup, where all the character components, with references to animation clips are on root of prefab, as is a standard.

However my character model, is ofc put under a specific child.

Now my question is, how to preview animation for the prefab model? 
Because:
- if Animancer is on root prefab object, the relative path to animated objects is incorrect (as seen in picture, yellow warnings)
- if I put Animancer on the CharacterModel, which is the actual model with animations, then there are no animations to preview, as the animation clips are in components in prefab root.
- 
![image](https://github.com/KybernetikGames/animancer/assets/12801017/af51e5d8-f062-483b-adb9-ee1c1d996728)

**Comment by KybernetikGames** [comment]
The `Animator` component definitely needs to stay on the model and the `AnimancerComponent` should be with it. That will have the Animation window call `AnimancerComponent.GetAnimationClips` to gather the animations for its list which first uses the rules explained in [AnimancerEditorUtilities.FindRoot](https://kybernetik.com.au/animancer/api/Animancer.Editor/AnimancerEditorUtilities/96511118) to figure out which object is the character's root, then gathers all animations under that.

Try implementing `ICharacterRoot` in one of your components attached to the root of the prefab. It should already be finding that object because it's inside a prefab, but there might be a bug in the code.
