### ISSUE TITLE
PlayableAssetState.Transition Speed doesn't work.

### ISSUE THREAD

**Issue by Cicaeda** [KybernetikGames/animancer#35]
# Environment

- **Animancer Version Number**: 4.3
- **Animancer Pro or Lite**: Pro
- **Unity Version**: 2019.3.3f1
- **Platform**: Windows

# Description

PlayableAssetState.Transition Speed doesn't work. For example, if you set the speed to 0.05x, it will still play as if it were 1x speed. However, the animation will continue to loop with the remaining calculated time. On the second loop, it plays the correct speed. If you set the speed to something higher than 1x, the animation will play at 1x speed, but just finish early.

Steps to reproduce the bug:

1. Do a timeline transition with speed other than 1x.

**Comment by KybernetikGames** [comment]
Changing the speed on the intro transition in the [Platformer](https://kybernetik.com.au/animancer/docs/examples/fsm/platformer/) example seems to work fine. Does the issue occur for you in that example?

Are you perhaps trying to change the speed on the transition after you have already started playing it? Because the transition only applied its speed during the `Play(transition)` call, any changes after that won't affect it until you play it next. If you want to actually change the speed of the playing state, you can set the `transition.State.Speed`.

**Comment by Cicaeda** [comment]
It turns out it wasn't Animancer's fault. I had a PlayableDirector on the same gameobject playing non-Animator component things like position/scale. It was somehow messing with the graph that Animancer was using despite not being bound to an animator. I separated it out and it works now. Sorry about that.
