### ISSUE TITLE
Layers and State Machines?

### ISSUE THREAD

**Issue by hrachid12** [KybernetikGames/animancer#351]
Recently purchased this asset and have been loving it so far. However, I am having trouble figuring out how to use layers with Animancer's FSM, and unless I've missed it, I haven't been able to find an example that utilizes both. Can someone point me to an example of this? Appreciate it!

**Comment by KybernetikGames** [comment]
Unfortunately, I've never worked on a system which required that sort of thing so I don't have any first hand experience in how to do it well, but I would start by making a script like `LayeredAnimationManager` in the [Dynamic Layers](https://kybernetik.com.au/animancer/docs/examples/layers/dynamic/) example, then have all your other scripts interact with it instead of directly with Animancer.

**Comment by hrachid12** [comment]
The reason I'm trying to use layers is because I have my character in a running state and I left click to attack, it changes to that state, however the legs don't look right since the character is still moving but the characters legs don't reflect that. I figured that I could use both. So is my best bet to not use a FSM? Are there any cons to not using one other than I may need to track state myself?

**Comment by KybernetikGames** [comment]
Have you considered having a separate FSM for each layer? I don't know how effective that would be, but it would more resemble what you'd see in an Animator Controller.

The only purpose of a FSM system is to manage your states so if you think Animancer's implementation is getting in the way of what you want to achieve then you should definitely consider doing it another way.

**Comment by hrachid12** [comment]
I'll give that a shot. Thank you!
