### ISSUE TITLE
Events are attached to the wrong state with HybridAnimancerComponent

### ISSUE THREAD

**Issue by Sahasrara** [KybernetikGames/animancer#37]
# Environment

- Animancer Version Number: 4.4
- Animancer Pro or Lite: Lite
- Unity Version: 2019.3.7f1
- Platform: OSX

# Description
I've created a single event for the 0.5f normalized time of an animation and instead of firing when the requested animation plays, it fires with a different animation plays.  Also, when it fires the first time, it fires off a huge number of events.

# Reproduction

```
AnimancerState state = animancer.CrossFade("Bouncer Standing Bouncing", 0f);
state.Events.Add(0.5f, () => { Debug.Log("I'm getting called when Bouncer Standing Idle South plays, and not Bouncer Standing Bouncing."); });
```

**Comment by Sahasrara** [comment]
It seems to have attached the event to an animation state called:

"Bouncer Standing Idle South"

instead of:

"Bouncer Standing Bouncing"

**Comment by KybernetikGames** [comment]
If `Bouncer Standing Bouncing` is a state inside the Animator Controller, then Animancer Events will not work properly because all the states in the controller are part of the same `AnimancerState` (a `ControllerState`) so it will trigger when any state in the controller passes the specified time.

So if you want events on those states you will need to use Unity's regular Animation Events.

I'll add an explanation about this to the documentation.
