### ISSUE TITLE
How to find the reference to [ClipTransition] in [TransitionAsset] under [TransitionLibraryAsset] in code

### ISSUE THREAD

**Issue by Lunch29** [KybernetikGames/animancer#378]
I don't know how to reference to the [ClipTransition] object in the [TransitionAsset] contained under the [TransitionLibraryAsset] class object , and I would like to mimic what the docs say about registering the trigger function with code on _Swing, the [ClipTransition] class object.
![屏幕截图 2024-12-12 135228](https://github.com/user-attachments/assets/5c316d3e-d208-4db3-a2bc-845389a5f604)
![屏幕截图 2024-12-12 134919](https://github.com/user-attachments/assets/c96ba8ac-8c31-424d-ae4e-a02186735c02)
![屏幕截图 2024-12-12 134951](https://github.com/user-attachments/assets/7d033d17-413e-4cf1-b5f4-f08ffa57b51c)
Hope you can help me, thank you very much!

**Comment by KybernetikGames** [comment]
Modifying the events of a Transition Asset is usually a bad idea because any modifications will affect every character using that asset, which almost always causes problems. 

The recommended approaches are to either register your callback in the [Central Events](https://kybernetik.com.au/animancer/docs/manual/events/animancer/usage#central-events) system or [give them to the state after playing it](https://kybernetik.com.au/animancer/docs/manual/events/animancer/usage#code).

**Comment by Lunch29** [comment]
Thank you, author, I fully want to use code to control registration events rather than drag and drop or click in the interpreter, which is easy to error. I want to configure the code registration function separately for each object that requires a lot of animation, so as to avoid problems with them as much as possible
