### ISSUE TITLE
Multiple clips require multiple controllers? 

### ISSUE THREAD

**Issue by BenVella** [KybernetikGames/animancer#380]
As per title, could I use a singer animancer controller to fire and manage multiple clips? Each one is to be told purely via code when to start, and how long to wait before restarting.

Also a followup question on any performance concerns / best practices whichever the recommendation goes. (one or multiple controllers)

**Comment by BenVella** [comment]
Looks like [layers](https://kybernetik.com.au/animancer/docs/manual/blending/layers/) would be the answer for this, but that seems not really any different than the Controller (And I'm not saying it should be).

I basically want every single clip to run on its own layer, and granted doing it programmatically would definitely be more convenient than messing around with the controller "noodle-fest".  Are there alternatives here or should this be the way?

And would something like the below be appropriate, to automatically assign each clip to its own layer, preventing the possibility of one ruining the other:

```cs
        for (var index = 0; index < clips.Count; index++)
        {
            AnimationClip clip = clips[index];
            AnimancerState state = animancer.Layers[index].Play(clip);
        }
```

**Comment by KybernetikGames** [comment]
I'm not really sure what you mean by "Animancer controller". Most of the samples have one script controlling multiple animations but you can control Animancer however you want.

Pro-Only features should be fully usable in the Unity Editor with Animancer Lite to let you try them out so most likely you're just misunderstanding how they work. If you want each layer to control different body parts or objects, you need to use Avatar Masks like in the [Basic Layers](https://kybernetik.com.au/animancer/docs/samples/layers/basic/) sample. Otherwise, the highest layer will just override everything the lower layers are doing.

**Comment by BenVella** [comment]
I see, masking would be irrelevant in my case. I have a tree with several branches and each clip moves an anchor along each branch. It will stop and wait until reset.

I was hoping to trigger each clip via the same component, potentially on separate layers without messing around with masks, since even though this is a single tree each branch could be considered as animating a complete lying independent branch with its own moving anchor

Is using layers while masking everything else the typical approach here?

Having seperate unique components for each branch should still be an alternative?

**Comment by KybernetikGames** [comment]
What you're describing sounds like having different animations control different body parts, which is exactly what masks are for.

That code would let you play multiple animations on the same layer without interfering with each other as long as you only play and stop them individually like that (you might need to create them on a specific layer rather than just in the States dictionary though, I don't have the code in front of me right now). I'm not sure if that will give the correct result or if it will try to blend all the currently playing animations, but it's worth trying if you want to skip making and managing masks.
