### ISSUE TITLE
Discord Channel?

### ISSUE THREAD

**Issue by bakyard** [KybernetikGames/animancer#40]
Please consider using Discord as viable means to support all KybernetikGames Unity assets.

Reasons for this:

- Very dynamic with lots of options for channels (like the old IRC), group participation, and organization
- Allows for many types of communication (voice, camera, video/picture/audio attachments)
- Cool interface!

Thank you

**Comment by KybernetikGames** [comment]
Unfortunately I've found that live communications are not very good for support. I used to have my Skype info listed and even though not many people actually used it, those people often required constant attention. Instead of reading the documentation and trying to figure things out themselves, they could just see that I was online and interrupt whatever I was doing instead. Some of the worst offenders even started trying to get me to help with totally unrelated topics.

Using email and forums takes away the expectation of getting an immediate response so that people will actually bother looking for solutions themselves first. Github Issues have been handling the task nicely so far. The only feature I think it's really lacking is a way for people to send me their projects privately so I can reproduce bugs, but that isn't needed very often so email has been fine for that.
