### ISSUE TITLE
GPU Animation

### ISSUE THREAD

**Issue by frostebite** [KybernetikGames/animancer#44]
# Use Case

To efficiently animate a large scene I have to use GPU animation. Currently I use Animancer for nearby LOD characters and another asset for GPU animation for characters further from the camera. However I frequently hit challenges with differences in the API. 

# Solution

It would be perfect if Animancer supported GPU texture based animation.

# Alternatives

Perhaps some testing could be done with 2-3 of the main GPU animation assets to compare their workflow and some examples could be made?

**Comment by KybernetikGames** [comment]
I definitely like improving performance (who doesn't?) but from what I've read it sounds like a monumental task (possibly bigger than everything Animancer currently does). I know practically nothing about GPU Animation or even the low level implementation of animation in general because Animancer doesn't do anything that low level, it just tells the Playables API what clips to play.

I'll put it on my list of things to look into, but I can't make any promises beyond that. It may also be somewhat dependent on the development of Unity's new DOTS based animation system (which I expect to suck even more than Legacy, Mecanim, and Playables did, but you never know) as well as the Scriptable Render Pipelines which apparently break shader stuff all the time.

Investigating and documenting the compatibility between Animancer and other plugins is a viable alternative in theory, but I already have a bunch of things people have requested I look at like Final IK, Puppet Master, and various visual scripting systems. It's just so frustrating trying to figure out what's what when I don't have a proper use case so I have no real idea what the actual users would need.

I'd be happy to share my thoughts on any specific problems you are having though.
