### ISSUE TITLE
Animancer Events - Auto Clear

### ISSUE THREAD

**Issue by DaPaKnat** [KybernetikGames/animancer#45]
Hello,

I would like to know if it's normal that this line of code being called one more time each time I play the animation is normal. If it is, then I didn't understand this part https://kybernetik.com.au/animancer/docs/manual/events/animancer#auto-clear correctly.

`
animancer.Play(animation).Events.OnEnd += () => Debug.Log("Test");
`

Thank you!

**Comment by KybernetikGames** [comment]
Can you elaborate on what you mean by "one more time"?

If you're referring to the way end events get triggered every frame after their time passes, then that is by design [as explained in the second dot point here](https://kybernetik.com.au/animancer/docs/manual/events/end/#events).

**Comment by DaPaKnat** [comment]
The first call to Play(animation): "Test" is printed once.
The second call to Play(animation): "Test" is printed twice.
The third call to Play(animation): "Test" is printed thrice.

**Comment by KybernetikGames** [comment]
That shouldn't be happening.

Could you please show me your full script so I can try to replicate the issue?

**Comment by DaPaKnat** [comment]
I managed to replicate the problem in the QuickPlay example.

1. Replaces AnimationClip with ClipState.Transition;
`
[SerializeField] private ClipState.Transition _Idle;
[SerializeField] private ClipState.Transition _Action;
`
2. Mark the end time in the inspector.
3. Add a Log in this function:
`
private void OnActionEnd()
{
            // Now that the action is done, go back to idle. But instead of snapping to the new 
           animation instantly,
            // tell it to fade gradually over 0.25 seconds so that it transitions smoothly.
            _Animancer.Play(_Idle, 0.25f);
 }
`

**Comment by KybernetikGames** [comment]
I changed `OnActionEnd` to:

```
Debug.Log("End");
_Animancer.Play(_Idle, 0.25f).Events.OnEnd += () => Debug.Log("Test " + Time.frameCount);
```

And it's logging everything as expected. When the action ends it logs "End" and after the Idle has played its first loop it starts logging "Test XXX" once per frame.

Are you perhaps adding your event to `_Idles.Events.Sequence.OnEnd`? Because the events on a transition do not get cleared, only the events on a state.

**Comment by DaPaKnat** [comment]
Here is the full code, I am sorry what I said wasn't clear enough. (Don't forget to mark the End Time to true in the inspector).

```
        private AnimancerComponent _Animancer;
        private ClipState.Transition _Idle;
        private ClipState.Transition _Action;

        private void OnEnable()
        {
            _Animancer.Play(_Idle);
        }

        private void Update()
        {
            if (Input.GetMouseButtonDown(0))
            {
                var state = _Animancer.Play(_Action);

                state.Events.OnEnd += OnActionEnd;
            }
        }

        private void OnActionEnd()
        {
            _Animancer.Play(_Idle, 0.25f);

            Debug.Log("Test");
        }
```

**Comment by DaPaKnat** [comment]
If the "End Time" is set to false, the log is correctly cleared.

**Comment by KybernetikGames** [comment]
I'm still not seeing any issues when running that and the End Time toggle definitely shouldn't be able to cause something like this.

Do you still have both characters in the example scene? Because they both have the same script so you might be getting confused by the fact that they log the messages at different times since their animations are different lengths.

If that's not the problem, then could you please send the scene file and script to animancer@kybernetik.com.au so I can take a look at it.

**Comment by DaPaKnat** [comment]
I sent you a mail with the scene and the script.

**Comment by KybernetikGames** [comment]
I found the problem.

When you play an `AnimationClip` it gets a spare event sequence from an object pool then clears and returns it when you play something else.

But each transition has its own event sequence so that it can be configured in the Inspector or on startup. Every time the transition is played it assigns that same sequence to the state and when you play something else the sequence is removed from the state but not cleared. So the problem was actually that you are using `+=` to add to the existing end event delegate every time and I couldn't replicate it because the original example used `=`.

If you are using transitions, you should initialise their events on startup to avoid this issue and because `state.Events.OnEnd += OnActionEnd` allocates some garbage so you don't want to do that every time (same with `=`).

I'll try to come up with a way to detect and warn about this issue in the future.

**Comment by DaPaKnat** [comment]
Thank you, I'll be careful using ClipState.Transition.

Le ven. 24 avr. 2020 à 16:15, Kailas Dierk <notifications@github.com> a
écrit :

**Comment by DaPaKnat** [comment]
I have one more question if possible.

How do I add a callback to the event of a sequence? Calling "SetCallback"
on the sequence replaces the callback entirely. Accessing the callback
property doesn't allow me to use += on it.

**Comment by KybernetikGames** [comment]
You could get the callback, use +=, then call SetCallback with the result.

Or you could go to the SetCallback method and make a copy of it that uses += instead. Not sure what it should be called though, maybe AddCallbackToIndex? I'm thinking I'll add a method like that to the next version.

**Comment by DaPaKnat** [comment]
That would be a good idea to give even more control to the script. Thank
you, your work is awesome!!!

Le ven. 24 avr. 2020 à 17:34, Kailas Dierk <notifications@github.com> a
écrit :

**Comment by KybernetikGames** [comment]
Happy to help.

If you haven't already left one, a review on the Asset Store would be greatly appreciated.
