### ISSUE TITLE
Examples Animancer v4.0 Beta - some have issues

### ISSUE THREAD

**Issue by LarsJandel** [KybernetikGames/animancer#5]
_Animancer Pro v4.0 Beta - Unity 2019.3.0f3 - Windows 10_

I know, you are still in the process of updating all the examples for the v4.0 release.
But anyway as I just had a look at all the examples: Almost all of them work fine. There are just three, which have issues - as far I could spot on some short tests:

- 06-01 Creatures: Clicking on the UI buttons has no effect
- 06-02 Interrupt Management: Clicking on the UI buttons has no effect
- 06-04 More Brains: The _Mouse Brain_ doesn't work. The character walk will get executed halfway on the first click and then stop. Any additional clicks or hold click will have no effect

These three examples work fine in a separate project on the same system using Animancer Pro v3.1.

Thanks

**Comment by KybernetikGames** [comment]
Thanks for being the first to open an issue. I would have responded faster, but this is my first time using Github Issues and I didn't realise I need to tell it to give me notifications.

That issue is easy enough to fix, you just need to select the UI buttons and re-assign the missing functions. Normally I only see this happen when I go back to Unity 2017.1 to export from that version (presumably the structure of the serialized data in UnityEvents changed after that version). I'm not sure how it managed to happen in my main project though.

**Comment by LarsJandel** [comment]
Thanks for the info about quickly fixing this issue!

**Comment by KybernetikGames** [comment]
I just released [Beta 5](https://kybernetikgames.github.io/animancer/v4-0/docs/changes/animancer-v4-0-beta/#beta-5) which fixes a build error and a couple of other minor issues (including this one).
