### ISSUE TITLE
Cross-fading "Play(ITransition, fadeDuration, FadeMode)" methods for MixerState 

### ISSUE THREAD

**Issue by ted-hou** [KybernetikGames/animancer#54]
# Use Case

<details>
<summary>
Background information
</summary>

I am authoring animations for different weapons (only animating the chest and arms), and the lower body is animated with a common set of MoCap data.

I have a _parent_ `MixerState` that uses an animation job to mix two _child_ `MixerStates`.
One _child_ `MixerState` plays legs/torso mocap animation, while the other _child_ `MixerState` animates the arms and a gun using authored clips.

Normally you would simply mix the two _child_ states using an upperBody `AnimancerLayer` and a lowerBody `AnimancerLayer`, but I had to use a _parent_ `MixerState` instead, because I needed to use an animation job to achieve some effects which would not be possible with an `AnimationLayerMixerPlayable`. The layer system still respects the Hips -> Chest -> Arms transform hierarchy, this means playing locomotion animation in the lower body layer will make the upper body shake and jitter around, which is undesirable especially from a first person perspective.

The animation job makes sure everything above the UpperChest bone (arms, weapons, and head) will be animated in _world space_, this way they would not be affected by the rotation of the Hips bone despite the transform hierarchy.

</details>

Currently `AnimancerLayer` has a few `Play` methods for creating a new state and playing it in the layer. This is really useful because you can instantiate child states on the fly, without worrying about  whether it has been created or not, and also have access to cross-fading effects.

However because I cannot use `AnimancerLayer`, and `MixerState` only seems to support a finite number of child states declared on creation. This makes cross-fading to a new animation using a `MixerState` cumbersome.

# Solution

Would it be possible to have something similar to `AnimancerLayer.Play(ITransition/AnimationClip, float, FadeMode)` but in `MixerState`? Or a special variant of `MixerState`?

# Alternatives

I guess the alternative would be to figure out a way to replace the `AnimationLayerMixerPlayable` with a `AnimationScriptPlayable`. I am not sure if that would be easier to implement.

**Comment by KybernetikGames** [comment]
It should be possible to do by making a copy of `ManualMixerState` and changing it to use a list instead of an array. Now that I look at it, I can see a lot of stuff in that class that should be moved up to the base `MixerState` so that such a copy doesn't need to duplicate so much code.

But I actually like the sound of the alternative better because that would let us directly use all the existing `Play` methods. I briefly tried to implement the `WeightedMaskMixer` from the jobs samples like that, but it crashed Unity so I just gave up because getting that script to be more generally useful would take a lot of work and I didn't have a clear goal in mind.

It should be pretty simple to implement a proof of concept:

1. Remove the `sealed` keyword from `AnimancerPlayable.LayerList` and give it a `protected` constructor that just sets the `Root`.
2. Inherit from that class and implement your own version of its original constructor which makes your job instead of the layer mixer.
3. Change `AnimancerPlayable.OnPlayableCreate` to use your class instead of the base.
4. Hope Unity doesn't crash.

I had removed this feature from my to-do list for v5.0, but if you can get the general idea working I'll take another look at implementing it properly.
