### ISSUE TITLE
How can I position a transform while previewing in the Animancer Transition Preview Window?

### ISSUE THREAD

**Issue by laughsuggestion** [KybernetikGames/animancer#55]
I have an animation of a spell cast and at a certain point in the animation I will play an event to cast a spell from a certain position. I'd like to use a transform to represent this position, but I do not know how to preview it. I should mention it's not a part of the animation, it's just a transform under the prefab.

In the image you can see that I can preview the animation, but it's not so easy to line up the transform with the hands. Any ideas?

![image](https://user-images.githubusercontent.com/1334646/86073970-cccb5000-ba39-11ea-941a-de7e0643c30c.png)

**Comment by KybernetikGames** [comment]
The easiest way to do that would probably be to create a sphere under the transform while you position it and use the regular Animation window to preview the animation in the scene rather than Animancer's Transition Preview window. Or even just do it in Play Mode: position it where you want it then just copy the character and paste after leaving Play Mode and copy the position over to your prefab.

Also, since the background is magenta I'm guessing you're using URP or HDRP which break the preview floor shader. If you download the [Animancer v5.0 Beta](https://kybernetik.com.au/animancer/docs/changes/animancer-v5-0/test) it will let you assign a custom material for the floor.

**Comment by laughsuggestion** [comment]
> The easiest way to do that would probably be to create a sphere under the transform while you position it and use the regular Animation window to preview the animation in the scene rather than Animancer's Transition Preview window. Or even just do it in Play Mode: position it where you want it then just copy the character and paste after leaving Play Mode and copy the position over to your prefab.
> 
> Also, since the background is magenta I'm guessing you're using URP or HDRP which break the preview floor shader. If you download the [Animancer v5.0 Beta](https://kybernetik.com.au/animancer/docs/changes/animancer-v5-0/test) it will let you assign a custom material for the floor.

Awesome, thank you for the quick reply. ALSO: I love this tool. I don't know if people tell you enough but, Mecanim blows and your tool is the best. Period.

**Comment by KybernetikGames** [comment]
I'm glad you like it. If you haven't already left a review on the Asset Store, that would be much appreciated.

**Comment by laughsuggestion** [comment]
> I'm glad you like it. If you haven't already left a review on the Asset Store, that would be much appreciated.

Will do!
