### ISSUE TITLE
Playing a looping ClipState.Transition with FadeMode.FromStart eventually freezes unity

### ISSUE THREAD

**Issue by zornor90** [KybernetikGames/animancer#61]
# Environment

- Animancer Version Number: v5.0
- Animancer Pro or Lite: Pro
- Unity Version: 2019.3.14f1
- Platform: PC

# Description

Inside of one of our scripts that handles reloading for our animation driven weapon system, we repeat the same animation (looping) until the gun has finished reloading. However, after about 23 times or so playing that animation, unity freezes each time the animation is played harder and harder until it takes about a minute or more per loop to complete. We noticed this when we added FadeMode.FromStart to the Play() function; before we added that, the animation would instead invoke the OnReloadEvent like 7 or 8 times randomly in the same frame

````
[SerializeField]
private ClipState.Transition _loopingAnimation;

private AnimancerState reloadState;

private AnimancerComponent animancer;

private void PlayLoopingAnimation() {
      reloadState = animancer.Play(_loopingAnimation, 0.25f, FadeMode.FromStart);
      _loopingAnimation.SerializedEvents.Sequence.SetCallback(0, OnReloadEvent);
      reloadState.Events.OnEnd += OnLoopingAnimationEnd;
    }

    private void OnLoopingAnimationEnd() {
      if (GetRemainingReloadCount() == 1) {
        PlayExitAnimation();
      } else {
        PlayLoopingAnimation();
      }
    }

    public void OnReloadEvent() {
      Debug.LogError("On Reload Event");
      gun.ammoClip.TryToReload(Engine.player.ammo);
      gunAnimator.onReloadEvent?.Invoke();
    }
````
I noticed that the issue didn't seem to happen (or at least, was less likely to happen) when I created the state using animancer.States.GetOrCreate, although then when I started caching the events and assigning them using AnimancerEvent.Sequence to the reloading animation, the issue started to happen once more.

# Reproduction

Steps to reproduce the bug:

You should be able to reproduce this with any animation, but if necessary we can try to provide a repro project! Thanks for all your hard work on this asset

**Comment by KybernetikGames** [comment]
The transition has its own event sequence which gets removed from the state when you play something but not cleared, so using `+=` instead of `=` on the end event will cause it to register a new copy of that delegate every time. So after 23 times, it will be calling `OnLoopingAnimationEnd` 23 times. I'm not sure what it could be doing that would freeze Unity for so long, but that's likely the root of your problem. I added warnings in Animancer v5.0 when you try to do that with regular events, but it looks like I didn't do it with end events.

When using transitions, I recommend initialising their events in `Awake` instead of re-assigning things every time you play them.

You also don't need to specify the fade duration and `FadeMode` in code when using transitions. If you enable the `Start Time` toggle in the Inspector, it will automatically use `FromStart` and whatever fade duration and start time you set there.

And instead of `.SerializedEvents.Sequence` you can just use `.Events`.

**Comment by zornor90** [comment]
Ah, you are absolutely right! Thanks for the clarification. Logging the output of the on end callback showed that each time the animation played the number doubled so eventually it was trying to run tens of thousands of callbacks...

I went ahead and moved the event initialization as well, good call on that!

One thing that I would like to mention is that the OnEnd getting called more than one frame has been a footgun for my team and I a few times, would it be possible to change that to only get called once and then maybe have a new event that uses the current behavior? Like AfterEnd or something

**Comment by KybernetikGames** [comment]
If you want it to only get called once, you can just use a regular event. The whole point of end events being separate is to ensure that they are always called even if you happen to only register the event after the animation has already passed the end.

**Comment by zornor90** [comment]
Okay - got it. Thanks for your time, glad it was a simple fix!
