### ISSUE TITLE
Some notes while following along Examples / 01 Basics

### ISSUE THREAD

**Issue by LarsJandel** [KybernetikGames/animancer#7]
I just finished going through the first section of the examples. I tried to follow along, recreate the examples from scratch in order to learn and memorize Animancer's workflow. Thanks for providing those. I wrote down some notes while doing so if you are interested in my experience.

Also thanks for including additional information as
- Coding Standard
- Default Script Template

Inspector Gadgets (Lite for now):
- very cool

Orbit Controls & Time Scale Scripts:
- quite handy, thanks

Tutorials - Examples 01 Basics:

- I think, all the basic examples should be follow-along tutorials, which isn't true for all of them (especially if being new(er) to Unity)

01.01 Quick Play:
- usage of "sealed class" could be explained, e.g. pointing to "Source Code / Default Scripts Template / Why sealed?" where you do so
- the mentioned "Golf" assets folder doesn't exist anymore, the "Golf Club" is inside "Props"
- sure, it's visible in the screenshot, but you could mention that "Holder.R" is a child of the right hand 

01.02 Playing and Fading:
- how to create and link buttons to public functions should be explained to be a follow-along tutorial:
    - in fact, it is explained within example 01.03 Sequence Coroutine...

01.03 Sequence Coroutine:
- all good

01.04 Named Animations:
- broken link: "Animancer Component Types" (...I did not try/click all of the links within Basics.)
- yes, learned before - just mentioning: not really follow-along tutorial regarding writing the script, e.g. defining the SerializeFields for the clips
- _Animancer.Layers[0].CreateState(_Walk); - hm, maybe explain where Layers[0] comes from / why it is set up like this

01.05 Hybrid Basics:
- describes the provided scene, is not a follow-along tutorial:
    - doesn't describe setting up the Animator Controller 
    - please show/describe setting up the toggle for walking: being a noob, I failed to use the "Dynamic bool" [_SetIsWalking_] entry for the toggle right away - used the "Static Parameter" one [_SetIsWalking(bool)_] first as previous examples/buttons always used entries down the list, what of course doesn't work...
    - I think it would help in the gif/screen recording if you would add numbers next to the toggle and buttons and repeat those next to the corresponding elements, which they trigger
    - please add a note, that "Run" will trigger the state in the Animator Controller which is named exactly like that. Because via drag n drop, a state is named after the animation clip, which won't work with the stated script using the modified name "Run".

Thanks

**Comment by KybernetikGames** [comment]
Those all sound like great suggestions and that's exactly the sort of feedback I like to hear.

01.02 Playing and Fading isn't a follow on tutorial because it isn't actually building towards a real outcome, it's just comparing the differences between play methods. Adding an explanation of how to set up UI buttons seems reasonable though. Maybe I'll even take it out of 01.03 Sequence Coroutine and have it as a separate page under Basic Scene Setup.

I'm somewhat reluctant to turn 01.05 Hybrid Basics into a follow on tutorial because the idea is that it lets you use existing Animator Controllers in Animancer alongside separate animations, but I don't actually want to encourage people to use them or have to answer support questions about them. Then again, maybe I should just keep my bias out of it and explain the available tools anyway.

**Comment by LarsJandel** [comment]
Cool, thanks.

**Comment by KybernetikGames** [comment]
- I've added an entirely new [C# in Unity](https://kybernetikgames.github.io/animancer/v4-0/docs/introduction/cs/) section which explains the basics of scripting so the examples can link there instead of needing to repeat things all the time.
- 01.01 Quick Play now has a [New Script](https://kybernetikgames.github.io/animancer/v4-0/docs/examples/basics/quick-play#new-script) section which points to an explanation of the `sealed` keyword (among other things).
- The Basic Scene Setup page now has a section explaining how to set up [Buttons](https://kybernetikgames.github.io/animancer/v4-0/docs/examples/basics/scene-setup#buttons) for 01.02 Playing and Fading and any other examples that use them.
- 01.04 Named Animations new uses a newly added `States.Create` method (which you obviously won't have in your version yet) so it doesn't need to mention layers at all.
- 01.05 Hybrid Basics has a few changes:
  - Added a new [Creating the Animator Controller](https://kybernetikgames.github.io/animancer/v4-0/docs/examples/basics/hybrid/#creating-the-animator-controller) section to go through it step by step.
  - [Walking](https://kybernetikgames.github.io/animancer/v4-0/docs/examples/basics/hybrid/#walking) now explains how to set up the toggle.
  - [Running](https://kybernetikgames.github.io/animancer/v4-0/docs/examples/basics/hybrid/#running) notes that it is the name of the state rather than the clip.
- Fixed all the other minor issues you mentioned too.

I've also addressed most of the things you mentioned in the other issues, but I'll need to go over them again to add links to the new C# in Unity section. In particular, it has more details about [Inheritance](https://kybernetikgames.github.io/animancer/v4-0/docs/introduction/cs/inheritance) and the [Vectors](https://kybernetikgames.github.io/animancer/v4-0/docs/introduction/cs/vectors/) page explains dot products, raycasting, and debug lines.

**Comment by LarsJandel** [comment]
Great - will have a look at the changes/updates in the next days. Thanks for doing this - hopefully these changes/updates are useful for others as well!

**Comment by LarsJandel** [comment]
I had a quick look at the new C# section: Nice, thanks for taking the time. Very useful for me! New Script section as well. 👍 I still have to look at all the other updates.
