### ISSUE TITLE
Setting a callback to AlmostOne is never called on no-frame animations.

### ISSUE THREAD

**Issue by Sahasrara** [KybernetikGames/animancer#71]
# Environment

- Animancer Version Number: 5.1
- Animancer Pro or Lite: Pro
- Unity Version: 2019.4.9f1
- Platform: MacOS

# Description

Setting a callback to AlmostOne is never called on no-frame animations.

# Reproduction

Steps to reproduce the bug:

             animationState.Events.Add(AnimancerEvent.AlmostOne, () =>
             {
                 Debug.Log("This will never be called if the animation has 0 frames");
             });

If I use OnEnd, the event IS called.  But AlmostOne doesn't work as I would expect.

**Comment by KybernetikGames** [comment]
Events don't really make sense on 0 length animations because they're based on normalized time which is `Time / Length`, meaning it's a divide by zero.

End events are specifically designed to always get called so that you never get stuck in an animation that can't end so it wasn't much of a stretch to do the same if length is 0 but I was reluctant to do the same with regular events.

But I suppose there probably isn't any real harm in invoking all events once per frame if the length is 0, so I'll take a look at it for the next version.

**Comment by KybernetikGames** [comment]
[Animancer v5.2](https://kybernetik.com.au/animancer/docs/changes/animancer-v5-2) is now available with this change implemented.
