### ISSUE TITLE
On AnimancerLayer.Weight

### ISSUE THREAD

**Issue by Jerry-04** [KybernetikGames/animancer#93]
![Lark20210111-152620](https://user-images.githubusercontent.com/26646837/104155106-6d56ef80-5421-11eb-9ffd-83a578b81a75.png)
The promblem I encountered was like: First I call  `AnimancerLayer.StartFade` with targetWeight set to 0 so that the animation in the current layer will play and gradually fade out in `fadeDuration`. Then in **next frame**  I call `AnimancerLayer.Play(state)` in the same layer. But with the code `if (Weight == 0 && TargetWeight == 0) Weight = 1;`, the Weight of this layer will not be set to 1 and still be 0 in the end. And the second Play will not be correct. Yet if I change the `&&` to `||` the problem will be fixed. So I'm trying to figure out whether this is bug or intentionally designed(if so, what situations  is it designed for?).

**Comment by KybernetikGames** [comment]
It was intentional, but it's an edge case where I'm not really sure what the ideal behaviour should be.

Usually if you're fading animations in and out you would use the `Play(state, fadeDuration)` method which calls `StartFade(1, fadeDuration)` to cancel your previous fade to 0. So the issue wouldn't come up if you were only using the fade methods or only using the instant methods, it's only because you're mixing them. That means you can avoid the problem by calling `Play(state, 0)` instead of `Play(state)`.

The reason I implemented it like that was to make it possible to directly control the weight of the layer (or fade it) independently of whatever animations you are playing on it. The exception being that `if` statement since having the layer stay at 0 weight and not be fading when you tell it to play something is unlikely to be what you want to do.

The main place that behaviour is used is in the `Play(state, fadeDuration, mode)` method where it calls:

```
StartFade(1, fadeDuration);
if (Weight == 0)
    return Play(state);
```

If the layer is at 0 weight and you want to fade an animation in, fading both the layer and the state in at the same time would have a noticeably different effect which is not usually what you want so that code makes it only fade the layer and immediately play the state. But if you change the `&&` to `||` then it would immediately snap both the layer and the state to full weight without fading either of them. That could be worked around with a bit more code (such as by splitting the rest of the `Play` method into an `InternalPlay` method so that `Play(state)` can set `Weight = 1` and call `InternalPlay` while `Play(state, fadeDuration)` only calls `InternalPlay`) but that doesn't seem like a very elegant solution to me.

What do you think? Should you just call `Play(state, 0)` when dealing with fading or would it be better to add a bit more internal complexity so that people don't run into this issue?

**Comment by Jerry-04** [comment]
Thanks for the reply!
I will call `Play(state, 0)` to fix my problem and I agree with you on that adding a `InternalPlay()` is not a good solution. Maybe you could add more remarks/annotation on `Play(state)`. The current description could be a bit of confusing to users.
![Lark20210111-174310](https://user-images.githubusercontent.com/26646837/104165548-7ef5c280-5434-11eb-8e50-6c1b51973a00.png)

**Comment by frankcarey** [comment]
I'm seeing strange behavior even if the layer isn't set to zero though.. In my case, the layer weight is pre-set when I create it to be a 0.75f, but as soon as I play the first animation it jumps to 1f instead. 

```
 // NoteL _AnimancerComponent.Layers[3].Weight = 0.75 above
 _AnimancerComponent.Layers[3].Play(animationClip, transitionDuration);
// Seems like the above Play() with a transition causes the layer's weight to go to 1f.
// I'm having to override it each time I play.
_AnimancerComponent.Layers[3].Weight = MyMaxWeight;
```

**Comment by KybernetikGames** [comment]
`Play` with a fade duration starts fading the layer weight towards 1 and if the fade duration is 0 then the weight will immediately be set to 1. As with OP's issue, that's by design but it's also an edge case where I'm not exactly sure what the ideal behaviour would be so I'm open to changing it.

**Comment by Flavelius** [comment]
I hope i'm not misunderstanding this, but wouldn't it work to just have an additional optional targetWeight parameter in play()?
Atleast it's somewhat in line with what i have in mind when using additive layers that may require fading in to lower weights.

**Comment by KybernetikGames** [comment]
I'm wary of adding anything to the Play methods because there are already 6 of them with optional parameters (8 if you include TryPlay).

In this case, I don't think trying to play something with a target weight other than 1 is common enough to be worth further complicating those method signatures.

**Comment by hariedo** [comment]
It's an old topic, long closed.  This was my workaround for doing a fadeIn AND setting a target weight for a layer:

```
            // if you .Play(clip, fadeIn), it forces a targetWeight=1
            AnimancerState state = animancer.Layers[layer].Play(clip);
            if (weight == 0f)
                weight = 1f;
            if (fadeIn > 0f)
                animancer.Layers[layer].SetWeight(0.001f);
            animancer.Layers[layer].StartFade(weight, fadeIn);
```
