### ISSUE TITLE
Animancer interfering with physics on bones?

### ISSUE THREAD

**Issue by avallintine** [KybernetikGames/animancer#94]
On my skeleton I have a chain of several bones where each bone has a Rigidbody and ConfigurableJoint. The idea is to simulate a "jiggle bone", like a tail. When I play a clip using Animancer, the physics on those bones doesn't work. They just remain "stuck" in their original pose. This happens _even when I exclude those bones using an AvatarMask on the layer_. The only thing I've found that works is to exclude those bone channels from being imported at all, using a mask in the clip import settings.

On the other hand, when I play the same clip using Unity's AnimatorController, the physics on those bones does work, whether I use a mask to exclude those bones or not.

Do you have any idea why Animancer and AnimatorController behave differently in this regard? More importantly, how can I get Animancer to not interfere with the physics on those bones?

Thanks!

**Comment by KybernetikGames** [comment]
I've never tried anything like that, but I would have expected Animancer to have the same behaviour as Animator Controllers since the Avatar Mask system isn't actually part of Animancer, it's part of the Playables API which is what Animator Controllers are built on as well.

Could you send a minimal reproduction project to animancer@kybernetik.com.au so I can take a look at it?

**Comment by avallintine** [comment]
Sure, I'll see what I can throw together. I admit, I was also puzzled by the difference in behavior, and it's entirely possible that I've overlooked something else that I'm doing to cause it.

Thanks for the quick response!
