### ISSUE TITLE
Integration with / Support for Mirror networking

### ISSUE THREAD

**Issue by ChaosCrazed** [KybernetikGames/animancer#95]
# Use Case

I'm looking to use Animancer (Pro) with Mirror to synchronize animations for a multiplayer project. For example, players seeing each other walk instead of sliding around in T-Pose position.

# Solution

As a new user of Animancer, I haven't delved too deeply into its source code to tell as of yet how it communicates with the Animator component. Mirror's [Network Animator](https://github.com/vis2k/Mirror/blob/master/Assets/Mirror/Components/NetworkAnimator.cs) component does use a reference to the animator, but doesn't appear to recognize what Animancer does as a change to synchronize.

My overall early thoughts at this point are either a change / addition to how Animancer makes animation changes, or perhaps a customized Network Animator script that can 'detect' Animancer's actions.

# Addendum
I am very much new to Animancer so I may have missed something in how to call animations entirely that would solve this. My apologies if this ends up as quite the dumb request.

**Comment by KybernetikGames** [comment]
Networking is one of the very few areas where the restrictiveness of Animator Controllers gives them a distinct advantage.

Directly synchronising animations isn't really possible due to the way Animancer works. Any script can tell it to play any `AnimationClip`, but they don't have any sort of inbuilt identifier that could be sent over the network for the other computer to get that same `AnimationClip`. Animator Controllers get around that by requiring all states to be pre-defined so they can be identified by a simple string or hash code.

Even if that problem could be worked around, doing so wouldn't be very useful. There's no point in having the client play an *Attack* animation if your scripts don't actually know that the character is attacking. That's not a problem with Animator Controllers because they operate on their own internal logic so your scripts already need to be constantly checking what state it's in. But Animancer doesn't do any decision making for you, it only plays what you tell it to so your scripts usually know what it's playing without needing to check.

Rather than trying to synchronise the animations directly, it would be much more useful to synchronise the scripts you are using to control the animations. If you're using Animancer's FSM, you could use a [Keyed State Machine](https://kybernetik.com.au/animancer/docs/manual/fsm#keys) with an enum key so that you can synchronise that key to tell the other computers which state a character is in along with whatever movement and other parameters you need. That means networking with Animancer is basically the same as networking any of your other scripts so there isn't really anything useful I could do to integrate Animancer with a particular networking system.

**Comment by ChaosCrazed** [comment]
Thank you for the detailed and quick response! Seems I’ve got a little rethinking to do!
